### ISSUE TITLE
Create handler / renderings for charts

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#113]
This depends on two work items being finished:

#68, so the charts preprocessor will be running on bach
#108, so the charts preprocessor is called when a chart is found by the top level categorizer

At this point, handlers should be seeing valid chart data, so can create audio/haptic renderings of the charts.

@florian-grond @johnnyvenom I don't know if you have received example JSON from the charts preprocessor to begin thinking about this before the above two work items are completed, but if you have time and have not received the JSON, please sync up with @gp1702 / @SiddharthRaoA to get example JSON.

**Comment by jeffbl** [comment]
This was postponed since the charts preprocessor was not viable. @jaydeep is now implementing highcharts (#129) so I'm restoring this as the work item for creating a handler that can render for the following demonstration examples (pulled from Slack discussion, subject to change if everyone agrees):

Line graph
https://etherscan.io/chart/tx

Bar chart: TBD from
https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec

Pie chart: Distribution of deaths by age group
https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec

**Comment by Cybernide** [comment]
I like the line graph and pie chart examples. Those are easy to understand and simple enough. Why don't we go with a TD bar chart for more variety? I think there was a decent example in server #129

**Comment by florian-grond** [comment]
Pls keep in mind that each chart type will likely call for wildly different sonification approaches and that we need to understand where to make the distinction, will the preprocessor call different handlers or will the handler call different synthesis approaches. does Hicharts have a "label" that helps to distinguish chart types?

**Comment by jeffbl** [comment]
All handlers are called. If there are three handlers for different kinds of plots, each of the 3 would run, but 2 of them would look at the chart type, say "not my type", and return nothing.

**Comment by jeffbl** [comment]
I'd argue that rather than such specific tags, it should be more like (with better names):

PlotType: bar/line/pie
NumberOfTrends: <number> (for bar charts, >1 means it is grouped? this might miss other bar chart types?)
MaxPointsPerTrend: <number>

Then, it isn't so closely tied to the preprocessors we're creating (i.e., by deciding what thresholds are important in the preprocessor), but the check within the handler is still trivial.

**Comment by florian-grond** [comment]
+1 to break down this info! in the way you suggest @jeffbl

**Comment by jaydeepsingh25** [comment]
Summarizing the supported chart types and data formats:
1. Chart number 1 (line chart):
•	Etherium: https://etherscan.io/chart/tx
•	Values to check for in data:
```
            x: represents unix timestamp
            y: represents number of transactions
            dt: Date represented by timestamp
```
2. Chart number 2 (Multi-line charts): 
•	Charts available at https://thoughtleadership.rbc.com/navigating-2021-21-charts-for-the-year-ahead/ (Chart no. 1, 2, 6, 8 are very similar) . In all these examples title is missing and only subtitle is present.
•	Values to check for in data:
```
x: x values if continuous data
name: (if exists, will represent category if x data is not continous)
y: y values of data
```
3. Chart number 3 (Pie Charts):
•	Following options are available:
o	https://www.worldometers.info/coronavirus/coronavirus-cases/ (includes title, subtitle missing)
o	https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec (both title and subtitle are missing)
•	Values to check for in data:
```
y : represents percentage in pie chart
name: represents the description for what category it represents
value: Numeric Value represent by the category
```
4. Chart number 4 (Vertical Bar Chart):
•	Chart available at https://thoughtleadership.rbc.com/navigating-2021-21-charts-for-the-year-ahead/ (Chart no. 10), Very similar data format with Line Chart
•	Values to check for in the data:
```
x: x values if continuous data
name: (if exists, will represent category if x data is not continuous)
y: y values of data
```

**Comment by jeffbl** [comment]
@jaydeepsingh25 should this be assigned to you, or to Juliette?

**Comment by JRegimbal** [comment]
Basic High Charts renderings added. Closing.
