### ISSUE TITLE
Implement text OCR preprocessor

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#114]
As we've seen with the charts preprocessor, text in images can be crucial for understanding, e.g., text on top of / next to wedges in a pie chart. However, the charts model does not currently extract this information, so although the user can know the percentage of different wedges, they have no idea what the wedges represent.

Task is to explore options for extracting text from images, and aligning/linking it with information from other preprocessors that extract locations of objects from graphics, like object detection or the charts preprocessor. Is this even feasible?

Note that for exploration with a haply, just adding the ability to read out text areas when hitting them may be enough in some cases, since proximity to other layers (like the wedges of a pie chart) may be enough to extract relevant meaning.

This capability may also be key for things like diagrams from textbooks, like the solar system graphic from the NFB demos.

**Comment by BenMacnaughton** [comment]
The Azure read API provides bounding boxes which should allow us to identify text contained within objects identified by other preprocessors

**Comment by jeffbl** [comment]
@BenMacnaughton @aidanwilliams09 I'm moving this to Jan31, but also changing title to "implement OCR preprocessor", rather than logging a new issue. Acceptable?

**Comment by BenMacnaughton** [comment]
Sounds good @jeffbl
