### ISSUE TITLE
Support French language renderings

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#152]
Logging to server, but this would impact many server components as well as extension, etc.

**Comment by Sabrina-Knappe** [comment]
@JRegimbal and I looked into this a bit more today- 
Here are the French models available for ESPnet:
https://github.com/espnet/espnet/tree/master/egs/polyphone_swiss_french/asr1
https://github.com/espnet/espnet/tree/master/egs/mboshi_french/st1

Neither of these has TTS built for it yet, so we would have to do that aspect ourselves. It is also worth noting that the first model is Swiss French, and the second is French French. Ideally, especially for a grant like MEDTEQ, our system would do Canadian French. However, the resources in terms of datasets for Canadian French are very limited.

@jeffbl There is a lab at Sherbrooke working on Canadian French datasets. If we decide this is important to us for MEDTEQ or some other reason, we could reach out to them and see what they are working on.

**Comment by JRegimbal** [comment]
French TTS added in the new `espnet-tts-fr` service in #530 using a tactotron model trained on the SIWIS dataset. This handles one (large) item for adding this support.

**Comment by jeffbl** [comment]
@notkaramel I think this is subsumed by other work items, but I'll leave it to you to resolve appropriately, or specify what is different about this item than the other existing french support items.

**Comment by notkaramel** [comment]
Noted! I think I will reference this work item on my epic, xor reference my summer epic here once it is finished since this was the base that I built upon. Will update soon!

**Comment by notkaramel** [comment]
August 21st, 2023: All `multilang` related components are updated and pushed to production (hooray :tada:). French renderings are now available to end-users!
