### ISSUE TITLE
Photo fails on wikipedia at one URL, but works at another

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#189]
Install IMAGE from Chrome Web Store v.0.1.0
Brave Browser, Ubuntu Linux
No screenreader active

Go to:
https://fr.wikipedia.org/wiki/Notre-Dame-de-Gr%C3%A2ce#/media/Fichier:Sreet_in_Montreal._Western_at_Prud'Homme_Ave_BAnQ_P48S1P03298.jpg

Right click photo with mouse
IMAGE extension --> get IMAGE rendering

NOTE: error: "An error occurred while trying to connect to the IMAGE server. Please try again later. If this error persists, please contact the IMAGE team by email at atp@cim.mcgill.ca."

Click on image to "magnify" it, and it goes to URL:
https://upload.wikimedia.org/wikipedia/commons/4/47/Sreet_in_Montreal._Western_at_Prud%27Homme_Ave_BAnQ_P48S1P03298.jpg

Right click photo with mouse
IMAGE extension--> get IMAGE rendering

NOTE: Correctly returns three renderings that are valid.

Something about the graphic accessed through the first URL makes it not work.

EXPECT: Able to get renderings for the graphic from either URL.

@JRegimbal - suggestions on who to assign to?

**Comment by JRegimbal** [comment]
Closing manually since this isn't a default branch.
