### ISSUE TITLE
Include streets and intersections in Autour query

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#198]
The current query excludes intersections, street segments, and transit information from the queries. All three should be included so that the handlers have the option of using this information. Sample query:

https://isassrv.cim.mcgill.ca/autour/getPlaces.php?framed=1&times=1&radius=250&lat=45.54294015139353&lon=-73.6263857486267&condensed=0&from=transit|osmxing|osmsegments|foursquare&as=json&fsqmulti=1&font=9&pad=0

**Comment by jeffbl** [comment]
Took a look, and to do this, I think this line:

https://github.com/Shared-Reality-Lab/IMAGE-server/blob/c330fe68fbd5f55e9982ea15ac7c519d64924df4/preprocessors/autour/autour.py#L83

needs to be changed from:
            `from=foursquare&\`

to:
            `from=transit|osmxing|osmsegments|foursquare&\`

After making change, or course, you'll need to verify that it doesn't break anything in the current handler, which may need an issue created to filter out things it is not currently interested in, but at least the extra data will be there for the current handler, or others who want to use it.

There may be complexities of which I am unaware, but it would be great to get this in asap so we can try it out?

**Comment by BenMacnaughton** [comment]
@jeffbl thank you for looking into this. I will be on a train all afternoon and can try to get this done tomorrow.
