### ISSUE TITLE
Determine future of "confidence" in the architecture

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#203]
Currently, confidence is meaningless. The values from preprocessors, if any, are garbage. The handlers can't actually use confidence for preprocessors to do anything and the handlers' own advertized confidence suffers from "garbage in garbage out".

This work item focuses on determining what should be done with "confidence", whether we redefine it, change the role, or remove it entirely from the schemas.

**Comment by JRegimbal** [comment]
Well, it's been over a month and there still isn't a use for confidence as it exists nor a story for how to make it useful. At this point, I lean towards removing it. Since the goal of this was to provide some mechanism for sorting/filtering renderings, is there another feature that may be worthwhile @Cybernide?

**Comment by Cybernide** [comment]
With regard to confidence being a wider scale, not preprocessor-specific feature, if we're not using it now and we don't have concrete, actionable ideas as to how to incorporate it, then toss it out or at the very least, move this into backlog.

**Comment by jeffbl** [comment]
If we really have no indication from the preprocessors whether they think they have done a good job, then I assume that we're more reliant on the user telling us what was useful to them, or aggregating stats on what renderings actually get played. This sounds dicey for March, so I'd say put in backlog for future consideration, if/when the number of handlers creating valid renderings becomes an actual problem.

**Comment by Cybernide** [comment]
We could potentially revisit this for when it comes time to put together a detailed user feedback form. Maybe it's my lack of imagination, but I don't know how else to use confidence here as it stands.
