### ISSUE TITLE
OSM data for better representation of streets (and other functionality?)

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#205]
The Autour data (#121, #198) includes information on street segments, intersections, and POIs. However, it does not include higher-level OSM functionality such as "ways" that assemble nodes into larger items like streets, which are not necessarily straight:

https://wiki.openstreetmap.org/wiki/Elements

This work item is to query OSM directly, rather than go through Autour, (or expand the Autour queries?) to get this additional information so that street-based renderings can be created.

Requirements here are driven by @florian-grond, @dreamseed87, and @johnnyvenom.

**Comment by jeffbl** [comment]
After discussion in tech-arch today, this is not quite far enough along to integrate in time for CSUN, so I am moving it past CSUN. @florian-grond @samueljohnsegun148 please let me know if we need to discuss. This is really a constraint on @jaydeepsingh25 's time for reviewing and helping to integrate this in time. Hopefully it can go in soon afterwards, since it would be great to have the additional maps experience for people to try!

**Comment by jeffbl** [comment]
@samueljohnsegun148 I'm very much hoping this can be merged by end of Jun27 sprint. Moving there.

**Comment by dreamseed87** [comment]
Sorry I did not catch this; but I guess I clarified requirement(s) for haptic rendering a while ago. (IIRC, I clarified most of them are already in the Autour quiries, and just asked not to eliminate them.)
Based on the experiences until now, if we additionally have polyline (ways) for guided navigation (in Force-feedback rendering), that would reduce our side's burden. (Well, from the coordinates of each "point of interests" we can calculate anything though.)

**Comment by jeffbl** [comment]
Yes, having the "ways" including intersections is one of the key goals of the OSM preprocessor, which we couldn't get using the Autour preprocessor (which will continue to exist, since it queries services other than OSM, and has a number of other advantages).

**Comment by samueljohnsegun148** [comment]
> @samueljohnsegun148 I'm very much hoping this can be merged by end of Jun27 sprint. Moving there.

@jeffbl Sure, I'm seriously working on it

**Comment by jeffbl** [comment]
@samueljohnsegun148 Can you close this now that the preprocessor is merged? If there are specific changes needed in the format, in consulation with @florian-grond they should be logged as new issues. Thanks!

**Comment by samueljohnsegun148** [comment]
Thanks @jeffbl. It is now closed.
