### ISSUE TITLE
Combine semantic segmentation and object detection into single rendering?

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#218]
For outdoor images, semantic segmentation might dovetail nicely if combined with the object recognizer. For example, from our demo page:

	"This picture of a fountain [as always wrong, but removed] contains 2 benches."
	https://nextcity.org/images/made/Minneapolis_LoringPark_920_568_80.jpg
	
Is pretty useless on its own. However, play Renderings 1 (semantic segmentation) & 3 (object recognizer) back to back. You then first get the larger scene context with the path and trees, and then when you hear the spatialized benches, you might retain some context for how they fit into the overall photo. @florian-grond  @Cybernide  I think this is potentialy much more powerful than having someone manually play both separately? Would there be a downside to combining these into a single rendering when both are available?

**Comment by Cybernide** [comment]
Will work on an interaction flow chart for this

**Comment by Cybernide** [comment]
@jeffbl Need more time to work on this, moving out if that's OK

**Comment by Cybernide** [comment]
@florian-grond So if I remember right, this is probably the data structure that you want to implement: https://link.springer.com/chapter/10.1007/978-3-642-72617-0_17

That being said, I don't know given the current architecture, whether this is feasible.

**Comment by JRegimbal** [comment]
Probably won't have time to dig into this until next week, but long story short if it can be serialized any data structure can be tossed around in the architecture. Whether or not it's convenient to work with inside some component is a different story.

**Comment by Cybernide** [comment]
I've drafted this, which we'll be discussing on Monday
![Audio-haptics interaction flow_ photographs (semseg and objdetect combined)](https://user-images.githubusercontent.com/7490996/149674968-18578a7e-abdf-47dc-977d-cd4cd9d07a10.png)

Compare and contrast with
![Audio-haptics interaction flow_ photographs](https://user-images.githubusercontent.com/7490996/149675003-c3d60dcc-4f4a-4595-880f-7871e42dc8da.png)

Is this a fruitful way to start?

**Comment by florian-grond** [comment]
@Cybernide thanks for putting this schema together, it looks like a fruitful way to start!

**Comment by Cybernide** [comment]
On consultation with the haptics team, interleaving the data as I presented above is too much to do, even for the March CSUN deadline. Suggest we move to backlog.

**Comment by jeffbl** [comment]
@Cybernide Does that mean we're not doing any combination by March? Not even serializing for audio? Or is that in a separate work item?

**Comment by Cybernide** [comment]
On further discussion, I believe the agreement is to make a rendering that concatenates semseg and objdet into one for the time being, and figure out how to interleave them in audio later. Is this doable in the given timeline?

**Comment by Cybernide** [comment]
OK, even easier, somewhat similar to Florian's suggestion above, can we combine the two in TTS for now, no audio, just plunk 'em next to each other. Semseg first, then object detection? @JRegimbal handing to you so you can tell me whether or not you can/are willing to do that for now.

**Comment by jeffbl** [comment]
Building on what @Cybernide said above, the idea is that if we have the segment names, then it would be the text-only handler would be the first effort to combine multiple preprocessor sources, as we intend to do for audio later, so we can begin seeing how that might shape up later if we decide to do audio contatenation. My assumption was that this would be a vasty simpler dev. effort since it would be adding on the discovered segment names to the existing object detection output, but if this is not vastly easier than the audio contatenation already discussed, then we should likely wait on this as well.

**Comment by JRegimbal** [comment]
@Cybernide Should be doable....I would like to refactor the supercollider side a bit to split out things a bit more nicely. Turnaround for open beta might compete with some other issues. I take it this should be prioritized over non-urgent items?

**Comment by Cybernide** [comment]
I'd say short of outright bugs, this should be up there - it's not as open-ended as other issues and as Jeff says, "low hanging fruit"
