### ISSUE TITLE
Clarify Graphics Terminology

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#224]
Currently, the various components of IMAGE use "image" to refer to the IMAGE project, graphics, and photographs. This has already lead to some confusion in conversation and since the project ~will ultimately be~ *has been* open sourced, schemas and public facing parts of containers should be clear in what names are used. Files where "image" is used to refer to graphics or photographs and not the project are in:
* [x] Schemas
  * [x] `request.schema.json`
  * [x] `renderers/simplehaptics.schema.json`
  * [x] `preprocessors/categoriser.json`
* [ ] Preprocessors (tbd)
* [ ] Handlers (tbd)

**Comment by Cybernide** [comment]
I am ALL FOR this issue. Please let me know if I can help.

**Comment by JRegimbal** [comment]
Thanks! If you have any related suggestions please make them! :slightly_smiling_face:

**Comment by Cybernide** [comment]
I've been trying to make these changes on the website for a while now, being specific when it's photographs, and in general terms (when it's not clear whether it's a photo, chart, or map), "graphic". Is the issue that these words need to be changed in the server code?

**Comment by JRegimbal** [comment]
In this specific issue, yes. The different components internally use the terms and include them in the JSON being sent around. User-facing, I think there's a bit less inconsistency, but there may be problems especially in the names of renderings returned to the client (although when we replace those soon it won't be an issue at all).

**Comment by sriGanna** [comment]
Just checking in to see if there is an outcome from this issue? If we were to use this in a schema what is the recommendation in terms of naming? @JRegimbal

**Comment by JRegimbal** [comment]
List of schema fields changed in a breaking way:
* first categorizer: "image" type is now "photograph"
* simple haptics renderer: "image" is now "graphic"
* request: "image" is now "graphic"

**Comment by JRegimbal** [comment]
Changes merged so this issue is closed!
