### ISSUE TITLE
setup cron job on pegasus  

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-server#245]
As mentioned in https://github.com/Shared-Reality-Lab/auditory-haptic-graphics-server/issues/227, we need to set up a nightly cron job to `docker container prune` and `docker image prune` to keep old cruft from accumulating.

**Comment by jeffbl** [comment]
There are more people migrating code to pegasus, so it would be good to get this set up sooner rather than later, since otherwise people will get used to it not doing it, and be surprised when it starts. If you can't get to this, please assign to @jeffbl and I'll do this one.

**Comment by jaydeepsingh25** [comment]
Closing the issue as cron job has been created on pegasus.

**Comment by jeffbl** [comment]
I don't think it is working. When I run `docker images --filter "dangling=true"`, I see a dozen or so dangling images that are older than a day?

**Comment by jaydeepsingh25** [comment]
Running the above command gives me no results on pegasus, hence closing the issue. A seperate bug could be logged if the cron job doesn't seem to work in future.
