### ISSUE TITLE
Graphic that used to work now gives error, depending on how it is accessed

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#248]
Linux Ubuntu 20.04 LTS HWE
Extension 0.1.0
Brave browser

https://en.wikipedia.org/wiki/Cooking#/media/File:Agdz-rosino-05.jpg

Get IMAGE context menu and request IMAGE rendering.

ACTUAL: `IMAGE is unable to render this graphic. Please note that IMAGE is still in pre-release development, so only works on a limited set of graphics. For working examples, please see https://image.a11y.mcgill.ca.`

EXPECT: Gives object detection / semantic segmentation results

Click "X" in upper righthand corner
Right click same photograph in small version embedded in overall wikipedia page and request IMAGE rendering

ACTUAL: Provides semantic segmentation and object detection results (correct)

Comments: IIRC, this used to give results when accessed via extension at the first link above. However, now it gives the above error. Filtering has been turned off, so semantic segmentation is now running whereas it didn't before, but I don't know if that is related to this issue. Could also be the image is too big, or that the webpage changed since I last tested.

**Comment by jaydeepsingh25** [comment]
It seems to work fine for me:
![image](https://user-images.githubusercontent.com/51749136/149257525-5a250ac8-b33f-4074-bad5-5b40c36f3fd0.png)
@jeffbl , can you please cross-check if you are still getting error for this image?

**Comment by jeffbl** [comment]
Confirmed just now using a build of the extension later than the one on google store. It seems it is just a image size issue, actually. I was using a very large browser window (vertical 4k screen) which is probably not common. If I do it on about 5/6 of the vertical height, I get the error. If I shrink the browser window down quite a bit, I get renderings. If you confirm this is the only issue, this is a duplicate of #187. (which would imply that one piece of advice in that error message might be to scale down your browser window, although that then begs the question why we wouldn't reduce the photo to a reasonable size before sending it up to the server...)

**Comment by jaydeepsingh25** [comment]
I see, i can only check on a standard 16'' display and it is working fine for me. But yes as you said, it may not work for larger screen sizes. Probably it is a duplicate issue of #187 then.

**Comment by jeffbl** [comment]
Let me know if there is anything else you want to see. It looks like the query is making it to traefik, which makes sense since I don't get the "couldn't communicate with server" error, but instead that it can't produce a rendering.

Looks like object-detection doesn't see it as image content:

atp-object-detection             | Not image content. Skipping...
atp-object-detection             | [2022-01-13 04:37:55 +0000] [31] [DEBUG] POST /preprocessor
atp-object-detection             | YOLOv5 🚀 v6.0-0-g956be8e torch 1.9.1+cu102 CPU
atp-object-detection             | 
atp-object-detection             | Not image content. Skipping...

Whereas when I scale it down, it does:

atp-object-detection             | [2022-01-13 04:39:32 +0000] [31] [DEBUG] POST /preprocessor
atp-object-detection             | YOLOv5 🚀 v6.0-0-g956be8e torch 1.9.1+cu102 CPU
atp-object-detection             | 
atp-object-detection             | Fusing layers... 
atp-object-detection             | Model Summary: 476 layers, 87730285 parameters, 0 gradients

**Comment by jeffbl** [comment]
@jaydeepsingh25 If this is truly a dupe of #187, can you mark it as such, and close?
