### ISSUE TITLE
Switching the Object Detection model from CPU to GPU

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-server#253]
The initial fix for issue [242](https://github.com/Shared-Reality-Lab/auditory-haptic-graphics-server/issues/242) was proposed in issue [250](https://github.com/Shared-Reality-Lab/auditory-haptic-graphics-server/issues/250). However, it appears that the latest version of object detection model is also incompatible with cuda 11.0.  Hence as a temporary fix the object detection model has been switched to CPU. 

However, the model needs to be switched to GPU when the CUDA 11.0 is supported by the developers.

**Comment by jeffbl** [comment]
Assigned to @rianadutta since we'd only do the work to put this on the GPU if it will buy us material gains, so it needs to be evaluated.

**Comment by jeffbl** [comment]
@rohanakut bringing this into sprint from backlog on the assumption this might now be trivial to do if CUDA11 support is in place, and if so, would be an easy way to boost performance a bit, esp. on pegasus, where the GPU is currently very underused? If this is still not easy due to CUDA issues, can be returned to backlog.

**Comment by rbazin** [comment]
@jeffbl I checked the code and it seems to be fully compatible with using a GPU, I see no reason not to use one. The only thing to be careful of is to allocate a big enough one. I haven't tried the model myself, but I believe that something on par with a TitanXP GPU would be adequate.

**Comment by jeffbl** [comment]
@rbazin This is done, and live on unicorn, correct? I don't think we've seen any issues, so are you ok with enabling this on pegasus now as well?

**Comment by rbazin** [comment]
@jeffbl It is ! It has been running for a while now, I believe it can be ran on Pegasus too.

**Comment by jeffbl** [comment]
Now running on GPU on Pegasus as well. Closing.
