### ISSUE TITLE
Reinstate filtering for some graphic categories

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#256]
In talking to @gp1702 this morning, he mentioned, for example, that due to #202, semantic segmentation will run on charts. For beta, I'm assuming we'll want to (carefully) reinstate some filtering. @cyan - I'm starting a list here we can add to, then discuss with @gp1702 for implementation as we test more graphics:

- [ ] Since we have no deployable chart preprocessor, any graphic recognized as a chart should return no results.
- [ ] ???

**Comment by Cybernide** [comment]
I'm not getting semantic segmentation (or anything otherwise) from graphics of charts. @jeffbl @gp1702 should I close?

**Comment by jeffbl** [comment]
If you're comfortable with what you're getting across the board, and don't think any of the older filtering should be restored, then yes.

**Comment by Cybernide** [comment]
Closing. We can revisit if things change, of course.
