### ISSUE TITLE
Weights for Object Detection cannot be downloaded 

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-server#265]
While building the object detection model, we need to download the weights from the server. Currently the wget command tends to do this. However, the weights are not getting downloaded from the server, leading to a build failure. 

The following is the error thrown while building the docker image
<img width="1437" alt="Screen Shot 2022-01-12 at 1 14 29 PM" src="https://user-images.githubusercontent.com/27781159/149198248-35144ba3-e905-4b44-9557-9d99685b3de7.png">

The 404 error is thrown even if the path is changed from bach to pegasus. This issue is currently blocking the fix for[ issue 60](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/60).

**Comment by jaydeepsingh25** [comment]
@rohanakut , you need to use the following URL to download the models in your dockerfile: https://image.a11y.mcgill.ca/models/objectDetectionWeights/yolov5x.pt

**Comment by jeffbl** [comment]
Note that using the image.a11y.mcgill.ca link means that if we ever have to retarget the production server again in the future, this should not break again... This is also why I shut down all the IMAGE containers on bach, so that we catch things like this.

**Comment by jeffbl** [comment]
Repoening and assigning to @rohanakut since this will result in a code change that should be PR'ed, correct?

**Comment by rohanakut** [comment]
Closing this since [PR274](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/274) is merged
