### ISSUE TITLE
Increase debugging output on semantic segmentation

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#289]
Currently, semantic segmentation only logs `POST /preprocessor` and no additional information. It would be extremely beneficial to include information on which HTTP response code it is returning at the debug level (200, 204, etc.). Any other brief, relevant information should also be added.

**Comment by rohanakut** [comment]
@JRegimbal Could you please elaborate on the type of information which is expected to be returned? As far as I know, currently, the semantic segmentation does return 204, 500 etc. Is there any other information that is expected?

**Comment by jeffbl** [comment]
This is just for logging. Right now, the only thing we see for semantic segmentation is this in the logged output on pegasus:

`atp-semantic-segmentation        | [2022-01-20 19:09:15 +0000] [9] [DEBUG] POST /preprocessor`

This tells us that it is being run, but it doesn't tell us what happens after. The server was in a state where semantic segmentation was not working, so we want the logging to show what is being returned, so we can watch what is happening, and figure out what is going wrong.
