### ISSUE TITLE
Large images OOM semantic segmentation

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#290]
Brave Browser on linux
Nightly extension build

Go to:
https://image.a11y.mcgill.ca/images/pexels-mikhail-nilov-6981101.jpg
(Aside: you can also right click this photo on the image.a11y.mcgill.ca homepage, and it will OOM from there as well, which is how this was found)
"Get IMAGE rendering" using extension
Note: No semantic segmentation results
Note: Server logs show OOM in semantic segmentation (see below)
Expect: If graphic is sized too large to fit in reasonable memory for semantic segmentation preprocessor, it should be scaled down first, before processing

Note: this is discussed in #175, where it is suggested that there be a settable environment variable for the max size an image should be, and scaled to that size if necessary to prevent runaway memory use. This way, it would be easily configurable on different servers/local installs to match hardware capabilities.

atp-semantic-segmentation        | [2022-01-20 19:19:03 +0000] [9] [DEBUG] POST /preprocessor
atp-semantic-segmentation        | [2022-01-20 19:19:06,385] ERROR in app: Exception on /preprocessor [POST]
atp-semantic-segmentation        | Traceback (most recent call last):
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
atp-semantic-segmentation        |     response = self.full_dispatch_request()
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
atp-semantic-segmentation        |     rv = self.handle_user_exception(e)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
atp-semantic-segmentation        |     reraise(exc_type, exc_value, tb)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
atp-semantic-segmentation        |     raise value
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
atp-semantic-segmentation        |     rv = self.dispatch_request()
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
atp-semantic-segmentation        |     return self.view_functions[rule.endpoint](**req.view_args)
atp-semantic-segmentation        |   File "/app/segment.py", line 222, in segment
atp-semantic-segmentation        |     pil_to_tensor)
atp-semantic-segmentation        |   File "/app/segment.py", line 133, in run_segmentation
atp-semantic-segmentation        |     segSize=output_size)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
atp-semantic-segmentation        |     return forward_call(*input, **kwargs)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/mit_semseg/models/models.py", line 46, in forward
atp-semantic-segmentation        |     pred = self.decoder(self.encoder(feed_dict['img_data'], return_feature_maps=True), segSize=segSize)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
atp-semantic-segmentation        |     return forward_call(*input, **kwargs)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/mit_semseg/models/models.py", line 482, in forward
atp-semantic-segmentation        |     x, size=segSize, mode='bilinear', align_corners=False)
atp-semantic-segmentation        |   File "/opt/conda/lib/python3.7/site-packages/torch/nn/functional.py", line 3731, in interpolate
atp-semantic-segmentation        |     return torch._C._nn.upsample_bilinear2d(input, output_size, align_corners, scale_factors)
atp-semantic-segmentation        | RuntimeError: CUDA out of memory. Tried to allocate 12.81 GiB (GPU 0; 23.69 GiB total capacity; 12.27 GiB already allocated; 4.20 GiB free; 15.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
atp-orchestrator                 | Error occured on fetch from semantic-segmentation
atp-orchestrator                 | FetchError: invalid json response body at http://semantic-segmentation:5000/preprocessor reason: Unexpected token < in JSON at position 0
atp-orchestrator                 |     at /usr/src/app/node_modules/node-fetch/lib/index.js:272:32
atp-orchestrator                 |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
atp-orchestrator                 |   type: 'invalid-json'
atp-orchestrator                 | }

**Comment by jeffbl** [comment]
Possibly related, and if not, should probably be broken out into a new bug. After OOMing, it seems that semseg can hold onto a big chunk of memory. At next request, it seems to drop again, but this could potentially impact other preprocessors that also need GPU memory. From earlier today, it was holding onto almost 18GB:

`496525 17899MiB 58624213f091   semantic-segmentation:latest`

**Comment by rohanakut** [comment]
@jeffbl if the image is scaled down just for semantic segmentation, then the coordinates generated by semantic segmentation would be different from the coordinates generated by the object detection. This is because Object Detection gets a bigger image while semantic segmentation gets a downscaled image. If the downscaling operation needs to be done, then that should be the first operation after the request is received. The downscale operation should be run even before the first categoriser is run. 

This would require changes in the schemas as well, as we need to communicate to the audio/haptics team the size to which we have downscaled the image.

**Comment by JRegimbal** [comment]
To clarify, we did go with normalized values. Everything reported by preprocessors is between 0 and 1, so this shouldn't be a significant problem. We also used to have some scaling done on the client (way back), but this ran into weird security issues in Chromium since the way we access the image file anyway is fairly hacky. It would make sense to add such a feature again IMO.
