### ISSUE TITLE
Small sized objects easily misinterpreted as being more prominent in photos than they actually are

### ISSUE THREAD

**Issue by Cybernide** [Shared-Reality-Lab/IMAGE-server#300]
Case in point, the horse in the "Andes" landscape photo of the tutorial page. It is maybe only a few pixels of a very, very large photo. People who hear the object detection rendering might assume that the horse is of greater importance than other, much larger areas of the photo such as the sky and mountains and stream.

As of speaking, @JRegimbal [has combined objects and segments in a single "photo" handler](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/299/), which should mitigate some of the confusion, that being said, we should probably think about ways we can improve on this

Suggested fixes:
In non-speech audio, tweak some of the thresholds for minimum and maximum gain: i.e. any object smaller than 1/100th of the total size of the graphic should have the minimum gain. Likewise, any object larger than 1/4th of the total size of the graphic should have the maximum gain. This way, the range of volumes will better convey object sizes relative to one another.
For the photo _overview_ or _description_, i.e. "this outdoor picture contains..." filter out objects that are smaller than 1/100th of the total size of the graphic.

Let me know if any of this is unclear. @jeffbl Given the implementation of the photo handler, I think this can be moved out further than restricted beta.

**Comment by Cybernide** [comment]
For posterity, and because I think the analysis might be helpful for future work, I'm putting Juliette's analysis of object sizes here before Slack swallows it up. This data is from the photos found in test_images and more_test_images in the UX repo. Note the extreme number of very small objects and the steep exponential curve.

![image](https://user-images.githubusercontent.com/7490996/156124721-4b3aff5c-ce62-4f0e-9180-b4d20ffc5edf.png)

**Comment by JRegimbal** [comment]
Currently in #372, most of the volume scaling is done within that section where most objects lie. This works fairly well in that range, but ignores differences on the larger end (10% and 80% will sound practically the same). I'm thinking that we may want to modify another property for relatively larger size objects and use volume for smaller objects, or vice versa.
