### ISSUE TITLE
Add functionality to temporarily store user data for opt-in support

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#314]
In order to provide meaningful support to people who submit feedback/bugs, we need a way to access request and response data when given the user's consent. It would also be more convenient to the user to give consent for a particular request after something noteworthy occurred rather than to give blanket consent on all requests after a point in time. For this to work, all requests and responses would need to be saved for a short amount of time (~1 hour max.) to provide a window to the user before this data is permanently deleted.

This data would need to be associated to a particular request_uuid and a periodic job would need to be created to purge old files that do not contain a marker indicating the user has consented to their continued storage and use. This issue is solely concerned with creating the functionality, off by default, to store the data in a suitable format so it can be used later.

**Comment by jeffbl** [comment]
Putting in Open Beta for now, pending permissions and approvals.

**Comment by JRegimbal** [comment]
Currently running on Unicorn with logging disabled.
