### ISSUE TITLE
Rename first and second classifiers

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#318]
These names are very generic and don't help describe what they do, or differentiate them from each-other. Open to suggestions on new names, but doing this would help when describing the architecture, and also, since the repo is public, help developers who want to use our code better understand what these preprocessors do.

**Comment by jeffbl** [comment]
@gp1702 If we could do this in the next few days, it would make some things a bit easier as we generate the new build process. If you'd like help coming up with names, ping me!

**Comment by jeffbl** [comment]
@JRegimbal is this easy for you to change along with the others you are updating? Please assign to @gp1702 if the modification should be made by preprocessor team.

**Comment by jeffbl** [comment]
It would be confusing to have wildly different names all over, so if we're doing this, let's take the pain up front and make it consistent. Are we talking about a huge number of places? This will only become more difficult later...

**Comment by JRegimbal** [comment]
Everywhere that uses them. So any dependent preprocessors plus any handlers that use that information for something.

**Comment by jeffbl** [comment]
After discussion with @JRegimbal and @gp1702 names should be:
first_categorizer -> image_preprocessor_graphic_categorizer
second_categorizer -> image_preprocessor_photo_tagger

**Comment by JRegimbal** [comment]
(Note that in docker image names these are joined by dashes rather than underscores and that in keys camel case is most commonly used!)

**Comment by jeffbl** [comment]
This is taking far too long. @JRegimbal can you please take this and finish it?
