### ISSUE TITLE
Configure unicorn daily reset of containers

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#332]
To ease testing on unicorn:

- [x] Create script to pull current main (unstable), build, and bring up IMAGE server
- [x] Every morning at 05h00, run the script in case a tester forgot to reset it
- [x] Possibly: copy fresh docker_compose.yml in case tester corrupted it, or mark it RO to make it harder to change
- [x] complete update of wiki page to explain how to use all of the above with `docker_compose.override.yml`

@jaydeepsingh25's script take:
cd /var/docker/atp/
rm docker-compose-override.yml
cd auditory-haptics-graphics-server
git checkout main
git pull
docker-compose build
cd ..
docker-compose stop
docker-compose up -d --force-recreate --build

**Comment by jeffbl** [comment]
In case we need to reference later, here are the changes (fyi to @jaydeepsingh25)

docker-compose.yml is not writable by anyone. To modify it, chmod it first, then update. This is to prevent people from changing the main docker-compose.yml instead of creating their own docker-compose.override.yml.

The cron job. Has to su to me since it needs credentials to pull latest from github. I use a private key that is only used for github from unicorn. Note that the logs are stored in my homedir, and are world readable if we need to see if anything went wrong.
```
jeffbl@unicorn:/var/docker/atp$ cat /etc/cron.daily/image_restoreunstable 
#!/bin/sh
su -c '/var/docker/atp/bin/restoreunstable' jeffbl > /home/jeffbl/cronlogs/restoreunstable.$(date "+%Y.%m.%d-%H.%M.%S")
```

The actual script
```
jeffbl@unicorn:/var/docker/atp$ cat ./restoreunstable 
#!/bin/bash -x

# removes any docker-compose overrides, and rebuilds everything from scratch so that
# what is running on unicorn reflects what is merged into main.

set -o errexit #halt script if anything returns error
rm -f /var/docker/atp/docker-compose.override.yml
cd /var/docker/atp/auditory-haptic-graphics-server/
git checkout main
git pull
docker-compose build
cd /var/docker/atp/
docker-compose stop
docker-compose up -d --force-recreate --build
cd -
```

Future tweak: kill any other containers running on network `image` since they are likely containers that were brought up outside the docker-compose.yml, and should be shut down.

**Comment by jeffbl** [comment]
Assigning to @jaydeepsingh25 for review. If all seems OK to you, please close, otherwise assign back to me with comments/requests.

**Comment by jaydeepsingh25** [comment]
may we can also add `git reset --hard` just before `git pull` to make sure working directory is clean and it does have any other changes (just in case, if someone changes some files). WDYT @jeffbl ?

**Comment by jeffbl** [comment]
we will likely switch to just using prebuilt images based on checkins to main, which would remove the git reset --hard, which @JRegimbal is setting up. Assigning to myself pending this.

**Comment by jeffbl** [comment]
@JRegimbal OK to assign to you to make this happen once you're comfortable with it? Work is changing the script to use the prebuilt images rather than building them from scratch, then I think this can be closed...

**Comment by jeffbl** [comment]
The script has now been updated to work with the updated docker-compose.yml in the server repo, which instead of building the images from scratch, pulls the already built ones. Initial script revisions by @JRegimbal, expounded on by @jeffbl:

```
jeffbl@unicorn:/var/docker/atp$ cat restoreunstable 
#!/bin/bash -x

# removes any docker-compose overrides, and pulls images from scratch so that
# what is running on unicorn reflects what is merged into main.

set -o errexit #halt script if anything returns error
rm -f /var/docker/atp/docker-compose.override.yml
cd /var/docker/atp/auditory-haptic-graphics-server/

# Even though  we pull already built docker images, keep the repo up to date
#   and maintain the dependency "config/express-common.env" that is still required.
git checkout main
# `could git reset --hard` here, but should probably just error out and let user deal with it
git pull
git submodule update --init

# Pull the latest built images
docker-compose pull

# Stop everything, including any containers on the image network that
#   weren't started with docker-compose
cd /var/docker/atp/
docker-compose stop
IMAGECONTAINERS=$(docker ps -q -f "network=image")
if [[ ${IMAGECONTAINERS} ]]; then
        docker stop $IMAGECONTAINERS
fi

# Bring all the containers back up
docker-compose up -d --force-recreate

cd -
```

**Comment by jeffbl** [comment]
@JRegimbal I think this is ready to close now?

**Comment by JRegimbal** [comment]
Yup I think we're good!
