### ISSUE TITLE
Create MOTD handler

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#334]
For indicating system issues or other key information, we have no way to contact users on an ongoing basis. This proposal is to create a [MOTD](https://en.wikipedia.org/wiki/Motd_(Unix)) handler that returns only a text string that can be configured on the server, ideally just in the docker-compose entry for the handler. This should be the first result shown in the renderings popup (thus, not requiring any browser extension changes). If the string is empty, no rendering should be returned.

Examples:
1. At CSUN, the server gets massively overloaded, so we add a MOTD, "The IMAGE server is severely overloaded, so quality of the results may be temporarily reduced"
2. We're testing a new handler and want to call attention to it for a couple weeks, "New interpretation available! If you send a meme graphic to IMAGE, you might get a fun surprise!"
3. We want some particular feedback: "We've changed how object detection works. If you get odd results, we'd love to hear about it, so let us know using the feedback link at the bottom of this page. Thanks!"

Extensions:
1. Implement a browser extension modification to put this in a "special" field that isn't a dropdown like the other handler results, to make it more apparent.
2. Allow HTML links directly from the result, so that we can point to more information if necessary.

**Comment by jeffbl** [comment]
Ping to @Cybernide for feedback/ideas/brainstorming, since this is primarily a user outreach tool.

**Comment by JRegimbal** [comment]
I'm pretty hesitant to encode this in a handler. It doesn't really make sense in the architecture since it is entirely separate from the request content. I think maybe an extra endpoint for the orchestrator (`/render/status`?) that returns a JSON message with status and an optional message that can be interpreted by a client.

**Comment by jeffbl** [comment]
OK, this requires some design work then, so assigning to Cyan. My hesitation to make it something "special" springs from the greater implementation load (browser extension modifications required to handle this new thing), as well as not being able to piggyback on other UI/features that may come in the future (e.g., if we allow users to turn off certain ones, this would automatically be removeable, etc.)

However, agree it would be cleaner to have it just be a field in the results popup window, so I'm fine with that direction as well.

**Comment by JRegimbal** [comment]
Fair enough. If we want something quick and dirty the handler works, but it will be presented as "Interpretation 1: System Status" or something like unless we do something in the extension to handle it separately.
