### ISSUE TITLE
Flask deprecation issue for Python flask app containers

### ISSUE THREAD

**Issue by BenMacnaughton** [Shared-Reality-Lab/IMAGE-server#359]
It seems that the flask version used in some Docker containers is no longer working and causes an import error. This was fixed for me by changing the flask and Werkzeug versions to 2.0.3

**Comment by jeffbl** [comment]
It looks like the only container with this issue is the second-categoriser, so assigning to @gp1702

**Comment by jeffbl** [comment]
Assigning to @JRegimbal to get this done for open beta.
