### ISSUE TITLE
Add in-line explanations of renderings.

### ISSUE THREAD

**Issue by Sabrina-Knappe** [Shared-Reality-Lab/IMAGE-server#371]
Add an audio segment as an mp3 file that explains how users can interpret a rendering. I will record a quick demo this afternoon for review by Jeremy, Jeff, and Cyan.

Tasks:

- [ ] Create Initial Demo
- [ ] Review language in demo
- [ ] Add demo into the .ts file so that it is added to the popup

**Comment by jeffbl** [comment]
Just talked with Juliette, and the take for this for CSUN is as follows (@Cybernide correct me if I've gotten anything wrong). Each rendering will have an optional field with a URL for a page that describes that rendering. Cyan will update the tutorial page for that to work for all our current renderings, likely as a tutorial#section link. We'll need a wireframe for @jaydeep to add the link to this in the browser extension rendering popup. Each rendering will have its own link, allowing anyone who adds a new rendering to point to their own resource for explaining it. @Sabrina-Knappe does that make sense?

**Comment by Sabrina-Knappe** [comment]
No. I'm a little bit confused- are we having a website page that will have the description? Is the description supposed to be specific to the rendering or just describe the technique?

**Comment by Sabrina-Knappe** [comment]
@jeffbl to make sure you see this

**Comment by Sabrina-Knappe** [comment]
(https://xd.adobe.com/spec/205d4652-e2ff-4aeb-7151-cdbffd27eebd-566c/)
Here's a link to the wireframe with a link to the rendering. Let me know what you think of the language used. @Cybernide @jeffbl

**Comment by jeffbl** [comment]
suggest (subject to @Cybernide weighing in): "Explanation of how to interpret this [rendering/interpretation]" rather than "show me" which implies a video to me? And if it is a link, I lean toward noun rather than imperative verb. (if it was a button I'd feel differently).

**Comment by Cybernide** [comment]
I generally like keeping my link/button text as active as possible: so I'm of the opposite opinion; "Explain this interpretation" gets my vote.

**Comment by Sabrina-Knappe** [comment]
Great, I’ll update the wireframe and send it to Jaydeep.

From: Cyan ***@***.***>
Date: Wednesday, March 2, 2022 at 6:26 PM
To: Shared-Reality-Lab/IMAGE-server ***@***.***>
Cc: Sabrina Knappe ***@***.***>, Mention ***@***.***>
Subject: Re: [Shared-Reality-Lab/IMAGE-server] Add in-line explanations of renderings. (Issue #371)

I generally like keeping my link/button text as active as possible: so I'm of the opposite opinion; "Explain this interpretation" gets my vote.

**Comment by Sabrina-Knappe** [comment]
https://xd.adobe.com/spec/205d4652-e2ff-4aeb-7151-cdbffd27eebd-566c/
<img width="616" alt="Screen Shot 2022-03-03 at 1 01 34 PM" src="https://user-images.githubusercontent.com/56092221/156624325-6920bd21-0250-4638-a71a-95f072186af8.png">
How's this? @Cybernide

**Comment by Cybernide** [comment]
Wonderful. Yeah, for future reference, one of the things I find most effective for text help features is to, as much as possible, make the user feel as if they are actively doing/requesting help, and not having it thrust upon them - active language helps with that, though you have to be careful not to put words into their mouth about their state of mind (i.e. - I am confused, please explain). Using nouns tends to feel "dry" for lack of a better expression.

**Comment by Sabrina-Knappe** [comment]
Great. Now if you can provide the links that these need to direct to, we can re-assign to Jaydeep for implementation.

**Comment by Cybernide** [comment]
It's not implemented yet, but the way this is working out is that these are the likely links:
https://image.a11y.mcgill.ca/pages/howto.html#interpretations-photos
https://image.a11y.mcgill.ca/pages/howto.html#interpretations-maps
https://image.a11y.mcgill.ca/pages/howto.html#interpretations-charts

Is that a good way of going about it, given the underlying extension code?

**Comment by Sabrina-Knappe** [comment]
Assigning Jaydeep for advice on how to proceed.

**Comment by jeffbl** [comment]
@JRegimbal would be responsible for making sure the links are embedded in the appropriate renderings
@jaydeepsingh25 would be responsible for taking that link and putting it on the renderings page as shown in the wireframe

So, I'm assigning to both of them on that assumption that you're saying this is ready for implementation. Note that we can likely adjust the URLs easily since that is server-side, but the UI in the extension will require a new version of the extension to be pushed through the Google Web Store, so making sure that is solid is a higher priority.

@Sabrina-Knappe I've unassigned you on the assumption this is good to go. If not, please take it back from jaydeep/juliette until ready for implementation.

**Comment by JRegimbal** [comment]
BTW I don't think breaking down on photos/maps/charts will work. There are different renderers for different ones of each. So if photos explains the photo-audio-handler produced rendering, that may be confusing for the photo-audio-haptic produced one. For charts, it'll vary from pie to bar to line etc. For maps we have an autour style one now, but IIRC this will also be joined by something based off of Florian's examples.

**Comment by JRegimbal** [comment]
@Cybernide @jaydeepsingh25 server-side code is ready in #389.
