### ISSUE TITLE
OCR preprocessor returns trivial text

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#380]
This graphic:

https://image.a11y.mcgill.ca/images/pexels-mikhail-nilov-6981101.jpg

returns this OCR:

`The following 1 lines were found in the image: -----`

I'm wary of having a heuristic that throws away certain results, but I expect this would be confusing to hear. Brainstorm ideas for rejecting results from azure:

- must contain a minimum number of [A-Z,a-z] characters
- must contain a minimum number of characters total
- if there is confidence in the azure results, see if filtering on it might clear out useless results

**Comment by BenMacnaughton** [comment]
There is confidence on the results, but only on a word-by-word basis. A line confidence might be able to be approximated and then used as a filter.
