### ISSUE TITLE
OCR preprocessor consumes ~1.5s - is this expected?

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#383]
Looking at the [plot in server#266](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/266#issuecomment-1057488143), the OCR preprocessor takes around 1.5s (and sometimes 2.5) to return results. There may be no issue here, but that seems long for a commerical cloud service. Can we check to see if there are any unnecessary delays caused by how we are using this azure api? I'm comparing to the graphic tagger running on azure showing more consistent reponse times around 300ms on the same graphics.

**Comment by BenMacnaughton** [comment]
For the Azure Read API 2 requests need to be made:
- Post request that a record for the analysis be published
- Get request to fetch the record

This may be contributing in part to the delay

**Comment by BenMacnaughton** [comment]
Additionally, I realized that the wait loop I created was pausing for a second if a record was not found before trying again. I have adjusted this to be 10ms and this seems to be speeding up the process
