### ISSUE TITLE
Highchart not working for daily price chart

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#395]
This chart does not give any rendering:
https://etherscan.io/chart/etherprice

Which is surprising since it is from the same site and extremely similar to this chart, which does work:
https://etherscan.io/chart/tx

**Comment by jeffbl** [comment]
Assigning to @JRegimbal since this is a handler issue in this case.

@JRegimbal on the off chance that the underlying data is the same, and it is just a matter of also enabling the "area" type, I'm leaving in CSUN. If not the case, please move to Mar31 on project board.

**Comment by JRegimbal** [comment]
Seems like it might be the same, but again each chart type supports lots of options and variation. There's a good chance it'll fail horribly with other examples.
