### ISSUE TITLE
Define and Document new Highcharts data format

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#397]
For beta, we pretty much take the data from highcharts as-is and pass it to the handlers. Issues such as different options and formats, along with [different chart types](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/395) need to be dealt with in a more general, and more robust, way. There are two approaches to this, or perhaps a combination of both:

1. Create or use an existing generalized intermediate chart format that sits between highcharts (and eventually other data sources) and the handlers, that is a well-defined schema for the types of charts IMAGE supports.
2. Use the highcharts api instead of grabbing the data directly from the chart, which may give some advantages in generalizing even within highcharts, and making it more robust to errors.

Right now, the implementation even for highcharts is likely fragile since there seem to be many options and ways of representing highcharts data, and it is unlikely the current IMAGE pipline handles all the permutations gracefully.

**Comment by jeffbl** [comment]
Revised title based on collaboration with Highcharts on making a more usable format for their charts. This work item now encompasses working with them directly to define and document a format to make using their charts easier, as well as serve as a format for mapping from other chart providers in the future.

**Comment by jeffbl** [comment]
Priorities (@Cybernide please weigh in based on user-value), so that we complete one type in the preprocessor and the handler can be working while preprocessor work moves to the next chart type:
1. single trend line charts
2. multi-trend line charts
3. pie charts
4. bar charts (vertical)
5. bar charts (horizontal)
6. candlestick charts

**Comment by Cybernide** [comment]
We haven't quite done a preliminary charts interview yet to ascertain user needs yet, but in my own day-to-day browsing (not IMAGE or research-related) I rarely ever come across multi-trend line charts. (@jeffbl tells me that that most financial sites will feature multi-trend line charts, which probably says something about my ability to manage my finances.) Maybe just continue what you are doing, and we'll have prioritization information for you once the interviews happen.
