### ISSUE TITLE
Create a list of specialized ML based models

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-server#443]
As mentioned in #220 , the Azure content tags would be used to categories the input image into different categories. On the basis of these categories we need to select the appropriate specialized models to get better quality renderings.

For example, for the mentioned image, the following tags are generated : "outdoor", "animal". Since the category is "animal" we should trigger a animal classifier which could determine the breed of the animal, the color of the animal and any other information necessary. 

Hence, in this issue the main aim is to create a list of different specialised ML models which would run based on the categories mentioned in [link](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-categorizing-images)
![Screen Shot 2022-06-13 at 8 33 54 PM](https://user-images.githubusercontent.com/27781159/173469335-2ee8b165-1f3b-4c8e-9e76-92623634716b.png)

**Comment by rohanakut** [comment]
@jeffbl could you put this issue in the appropriate sprint?

**Comment by jeffbl** [comment]
Note that Azure has this functionality as "[domain specific models"](https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-detecting-domain-content), although they only have landmarks and celeberties, so it sounds like this would be using the mentioned API and adding on your own generated models for other categories.

**Comment by rohanakut** [comment]
A list of models which could be used for this issue:
**Celebrity Recognition:** https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-detecting-domain-content
**Landmark Detection:** https://docs.microsoft.com/en-us/azure/cognitive-services/computer-vision/concept-detecting-domain-content
**Emotion Detection:** https://github.com/serengil/deepface

**Comment by jeffbl** [comment]
@rohanakut Is there a new work item for this, to actually implement these as part of your thesis work? If so, should this be closed, if this is the final list you're going to use?

**Comment by rohanakut** [comment]
@jeffbl Closing this issue, since #455 would deal with the implementation of the models mentioned above
