### ISSUE TITLE
Extract the text present near an image for further processing. 

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-server#444]
Currently the extension sends only an image to the server. However, there is a provision to send text nearby the image to the server. For example, most of the images in [news articles](https://www.cbc.ca/news/world/kramatorsk-ukraine-elderly-escape-1.6486653) are accompanied with figure captions. These captions do not describe the image but they contain the necessary context to get better quality renderings. 

The main aim of this issue would be to find a way to extract these figure captions from the image and send it to the server for further processing.

**Comment by rohanakut** [comment]
@jeffbl could you please add this to the appropriate sprint?

**Comment by jaydeepsingh25** [comment]
As discussed with @rohanakut , I have implemented the following functionality:

- If the parent of the graphic clicked has some content, I pass the DOM(in a string format) of parent element to the server. 
- If the parent element does not have any information, I pass the prev and next sibling of the parent to the server, as they have the image context.

On the server side, the context field needs to parsed to get the useful text information.
