### ISSUE TITLE
Upgrade traefik to latest

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#463]
On unicorn and pegasus we're running traefik 2.4. 2.8 is in RC now. Before end of IGNITE funding, suggest we upgrade to current latest, which I assume will be 2.8. From the [migration guide](https://doc.traefik.io/traefik/v2.8/migration/v2/), I don't see any likely issues, but we'd want to start with this on unicorn, test, then update pegasus as well.

**Comment by jeffbl** [comment]
Actually, it appears that [2.x releases are supported only for about 6 months](https://doc.traefik.io/traefik/v2.8/deprecation/releases/), so 2.4 is not under active or security updates for about a year now!

**Comment by JRegimbal** [comment]
Already updated on Unicorn and no issues. If everything continues working there (which it should) we should be fine to update Pegasus.

**Comment by JRegimbal** [comment]
Traefik up to date on both systems.
