### ISSUE TITLE
Rendering audio level consistently lower than screen reader volume

### ISSUE THREAD

**Issue by Sabrina-Knappe** [Shared-Reality-Lab/IMAGE-server#477]
When playing the renderings in the extension, the volume of the spatialization is consistently lower than the volume of the screen reader, to the point where it can be difficult to hear the spatialization with the volume of the speech at a comfortable level. Some efforts to address this would be good.

Assigning to Juliette for investigation/implementation.

**Comment by jeffbl** [comment]
This seems like a signifcant usability issue if it is a wide disparity. Moving to one of the new 3-week sprints to get this deployed more quickly, especially if it may involve a browser extension update. (@JRegimbal please push back if you feel this should be moved later)

**Comment by JRegimbal** [comment]
No, now is good. It's important and should be server side since I tried to set audio file mean loudness to broadcast specifications, which are lower than is typically used in computer applications (e.g., streaming).
