### ISSUE TITLE
Nodes returned by OSM Preprocessor are way outside of the expected bounds

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#510]
While streets/ways seem to always run through the expected region queried, the actual nodes that make them up go well outside of the bounds. An example of this is plotted below with the rectangle covering the boundary specified by the `bounds` key. All other lines are various streets and ways. Note that if all of the nodes were rendered naively (as we are normally doing), the actual output would be massively different from what would be expected if only the bounded region were used.

![Figure_2](https://user-images.githubusercontent.com/6963142/197252738-18a025d9-00aa-4f6f-932d-f7c427411b99.png)

**Comment by samueljohnsegun148** [comment]
That's true @JRegimbal. The removal of duplicate intersections/POIs (#507) is now done. A [few changes](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/509/commits/1f4e3c60ad7047565f9cbc5d8844ff2b776b6f2b) to the lines of code was made in the OSM preprocessor.  So also is the restriction of returned nodes to those within the boundary, and it seems now to be working as expected. It is addressed [here]( https://github.com/Shared-Reality-Lab/IMAGE-server/pull/509/commits/23333c659e322a90d9ace3dbcdf842da9b8d3de6). All these changes are in the #509 PR.
