### ISSUE TITLE
maps: investigate navigation use-case

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#511]
from tech-arch this morning, discussion of other maps use cases for audio-haptic rendering. One we don't currently cover at all is the pre-planning of choosing a start and endpoint, getting step-by-step instructions for walking, and then getting an impression of the actual route through audio/haptics.

- How would this use-case be prioritized vs. the existing autour-like and OSM-streets-based preprocessors/handlers currently implemented?
- How would it work? Would there be an audio-only version, or would this be dependent on haptics?
- User study/survey on needs for this?

Assigning first to @cyan for thinking/evaluation (in backlog).

**Comment by Cybernide** [comment]
Closing @jeffbl
