### ISSUE TITLE
Basic "Glances" View of a Running Server

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#538]
Currently, the only way to know what is running on an IMAGE server instance is to run check the compose file, check the running containers, and do a series of other commands. To improve system visibility for maintenance, development and testing, a script should be made that displays a snapshot of the following information at a moment in time:

1. The name of the orchestrator component running.
2. All connected preprocessors including their image name, version, and priority position.
3. All connected handlers including their image name and version.
4. Reach: services running that are present in the active docker-compose (these are not currently advertised so this may be difficult). Uptime.

## Possible paths to implementation

* Standalone script: calls are made directly to the docker daemon to extract this information using an orchestrator container as an argument (or a docker-compose.yml file, or something else). This will provide an overview, but run-level information will not be easily available.
* Intetgrate into the orchestrator: a restricted HTTP endpoint is added to the orchestrator container. This will directly report on its connections. Note that this may make finding non-advertised containers more difficult (e.g., supercollider, ESPnet), but these will still be on the same virtual network and should be findable. This may have security implications, but there is a clearer path to determining what has happened during a particular request and visualizing (i.e., which preprocessors returned new data, which ones couldn't handle it, which ones errored, the outputs from each handler, elapsed times).

Assigning to myself to determine an actual implementation plan.

**Comment by JRegimbal** [comment]
First pass at this. It handles criteria 1-3, but cannot get services. Unfortunately, there wouldn't really be a way of distinguishing a service like TTS from another container like nginx as of now. One possible long-term idea would be wrapping the helper services in with the service discovery that the orchestrator already does, although this would require significant changes to the handlers, services, and orchestrator.

```bash
#!/bin/bash
# USAGE image-summary orchestrator_name


if [ $# -ne 1 ]; then
    echo "One argument required"
    echo "USAGE: image-summary orchestrator_name"
    exit 1
fi

orchestrator_name=$1

# Check for commands
if ! command -v docker > /dev/null; then
    echo "Docker is not installed or not on the path!"
    exit 1
fi
if ! command -v jq > /dev/null; then
    echo "jq is not installed or not on the path!"
    exit 1
fi

# Determine networks connected to the orchestrator container
orchestrator_networks=($(docker inspect $orchestrator_name | jq '.[0].NetworkSettings.Networks | to_entries | map(.value.NetworkID) | @sh' | tr -d \'\"))
preprocessors=()
handlers=()

# For all networks, get the connected, running preprocessors and handlers
for network in "$orchestrator_networks"; do
    for id in $(docker ps -f network=$network -f status=running -f label=ca.mcgill.a11y.image.preprocessor --format "{{.Label \"ca.mcgill.a11y.image.preprocessor\"}},{{.ID}}"); do
        preprocessors+=("$id")
    done
    for id in $(docker ps -f network=$network -f status=running -f label=ca.mcgill.a11y.image.handler=enable --format {{.ID}}); do
        handlers+=("$id")
    done
done

# Order preprocessors by priority group
IFS=$'\n' sorted=($(sort <<<"${preprocessors[*]}"))
unset IFS

# Display information
group=""
echo "Containers connected to orchestrator \"$1\""
echo "****************************************************"
echo "Preprocessors:"


for preprocessor in "${sorted[@]}"; do
    IFS=','
    read -rasplit<<< "$preprocessor"
    unset IFS

    if [[ $group -ne ${split[0]} ]]; then
        group=${split[0]}
        printf "\tPriority Group $group:\n"
    fi

    printf "\t\t$(docker ps -f id=${split[1]} --format '{{.Names}} ({{.ID}}) using {{.Image}}')\n"
done

echo "****************************************************"
echo "Handlers:"

for handler in ${handlers[@]}; do
    printf "\t$(docker ps -f id=$handler --format '{{.Names}} ({{.ID}}) using {{.Image}}')\n"
done
```

**Comment by JRegimbal** [comment]
With an obvious improvement
```bash
#!/bin/bash
# USAGE image-summary orchestrator_name

set -e

if [ $# -ne 1 ]; then
    echo "One argument required"
    echo "USAGE: image-summary orchestrator_name"
    exit 1
fi

orchestrator_name=$1

# Check for commands
if ! command -v docker > /dev/null; then
    echo "Docker is not installed or not on the path!"
    exit 1
fi
if ! command -v jq > /dev/null; then
    echo "jq is not installed or not on the path!"
    exit 1
fi

# Determine networks connected to the orchestrator container
orchestrator_networks=($(docker inspect $orchestrator_name | jq '.[0].NetworkSettings.Networks | to_entries | map(.value.NetworkID) | @sh' | tr -d \'\"))
handlers=()
preprocessors=()
# For all networks, get the connected, running preprocessors and handlers
for network in "${orchestrator_networks[@]}"; do
    for id in "$(docker ps -f network=$network -f status=running -f label=ca.mcgill.a11y.image.preprocessor --format '{{.Label "ca.mcgill.a11y.image.preprocessor"}},{{.Names}} ({{.ID}}) using {{.Image}}')"; do
        preprocessors+=("$id")
    done
    for id in "$(docker ps -f network=$network -f status=running -f label=ca.mcgill.a11y.image.handler=enable --format '{{.Names}} ({{.ID}}) using {{.Image}}')"; do
        echo "Entry"
        echo $id
        handlers+=("$id")
    done
done

# Order preprocessors by priority group
IFS=$'\n' sorted=($(sort <<<"${preprocessors[*]}"))
handlers=($(sort <<<"${handlers[*]}"))
unset IFS

# Display information
group=""
echo "Containers connected to orchestrator \"$1\""
echo "****************************************************"
echo "Preprocessors:"


for preprocessor in "${sorted[@]}"; do
    IFS=','
    read -rasplit<<< "$preprocessor"
    unset IFS

    if [[ $group -ne ${split[0]} ]]; then
        group=${split[0]}
        printf "\tPriority Group "$group":\n"
    fi

    printf "\t\t%s\n" "${split[1]}"
done

echo "****************************************************"
echo "Handlers:"

for handler in "${handlers[@]}"; do
    printf '\t%s\n' "${handler}"
done
```

**Comment by JRegimbal** [comment]
Added to image bin folders on Pegasus and Unicorn and working as expected. Closing for now (since there's no PR to make), but ping if there are any changes you would like @jeffbl.

**Comment by jeffbl** [comment]
Nice! I've been running it with `watch -n 60` for a couple days to see if any problems, and seems to be working fine. Only nitpick is the output is extremely wide, so hard to read in a tmux pane. Fine as is, but if you're updating in the future, suggest a flag to remove everything past "using" so that it it is easier to visually monitor the running IMAGE tools over time.
