### ISSUE TITLE
Enforce Renderer Advertisements in Orchestrator

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#541]
Currently, handlers are expected to not return any renderings in a renderer format that is not advertised by the client. Only renderings in a requested format may be returned. This is not currently enforced in the orchestrator and this behavior is supposed to be checked by PR reviewers. However, this has not been done consistently.

This issue will be resolved when an orchestrator will log an error and *refuse to append* renderings that are not in an advertised format.

Pinging @jeffbl for comment, assigning to myself as the orchestrator person.

**Comment by jeffbl** [comment]
Makes perfect sense to me. Please wait to enforce until #542 is completed, since otherwise the current SVG functionality will break.

**Comment by jeffbl** [comment]
Also please make sure there is a debug message output so that we know this is happening.
