### ISSUE TITLE
Object detection boxes and segmentation outlines from SVG debug do not align with actual object locations

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#570]
This appears to be a regression or uncaught case similar to [browser#280](https://github.com/Shared-Reality-Lab/IMAGE-browser/issues/280). 

Install test extension from Chrome Web store
Use options to target unicorn rather than pegasus
Bring up this photo
https://media.cnn.com/api/v1/images/stellar/prod/230213132111-02-vuhledar-extra.jpg?c=16x9&q=h_720,w_1280,c_fill

Look at the object detection SVG rendering
Note: rectangles for category "people" miss the actual people in the photo

![image](https://user-images.githubusercontent.com/2095406/218567480-e26628fe-343e-470a-aac4-37c319a820aa.png)

**Comment by emmanuelwilson** [comment]
Found that this problem also translates to the segmentation portion of the SVG handler on top of the object detection. 

To reproduce:
- Windows Chrome Extension
- test extension on unicorn

Photo link: 

https://unsplash.com/photos/tRDGs9utMUo

The offset is found in both object detection and segmentation, here is what the segmentation looks like: 
The segments are well placed relative to each other but do not fit in the graphic as can be seen. The segments and the objects are all shifted by the same amount.

![badsvgseg png](https://user-images.githubusercontent.com/25232146/220393768-6c6e6d68-de18-45c5-b3bf-e25933486fa7.jpg)

**Comment by jeffbl** [comment]
I can no longer reproduce this running the current test extension against unicorn, so I think recent changes to the SVG overlay functionality in the extension have corrected this, at least for these two cases. @emmanuelwilson if you agree, please close.
