### ISSUE TITLE
STORY: As a handler developer I want access to emotion, clothing, and celebrity information on people found in photos, so that I can provide a richer description

### ISSUE THREAD

**Issue by rohanakut** [Shared-Reality-Lab/IMAGE-server#586]
- [x] #579 
- [x] #580 
- [x] #581 
- [x] #582 
- [x] #583
- [x] #584 
- [x] #585 
- [x] #636 
- [x] #637 
- [ ] README files in git for each preprocessor and handler

**Comment by jeffbl** [comment]
Closing since latest from Rohan is merged, Note new issue #825 for dealing with remaining issues
