### ISSUE TITLE
Files stored for debugging should be automatically deleted after a certain time

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#592]
Currently, files stored for debugging purposes using the `/authenticate` endpoint in the orchestrator must be manually deleted. These should be automatically cleaned up after a long enough time that any issue should either have the data saved elsewhere for debugging purposes or should no longer be relevant.

@jeffbl I think 60 days is probably a long enough amount of time to not cause problems, thoughts?

**Comment by jeffbl** [comment]
60 days seems safe to me.
