### ISSUE TITLE
STORY: As a haptic experience designer, I want to understand the needs of stock traders who are blind, so that I can design a handler that creates experiences that meet these needs

### ISSUE THREAD

**Issue by lankwuit** [Shared-Reality-Lab/IMAGE-server#593]
- [ ] Summarize literature and commercial products on existing stock chart representation for people who are blind or low vision
- [ ] Summarize and prioritize user requirements and goals for understanding stock charts

**Comment by jeffbl** [comment]
@lankwuit checking in on this. Is it closed to being completed? If not, this should be moved to backlog or a current sprint?

**Comment by lankwuit** [comment]
> @lankwuit checking in on this. Is it closed to being completed? If not, this should be moved to backlog or a current sprint?

Hey Jeff, this should be closed already. Sorry I have not yet done so. I will have another story for this sprint on the board soon

**Comment by jeffbl** [comment]
@lankwuit Can you put a link here to where the summary is?
