### ISSUE TITLE
Include necessary features in open street maps preprocessor output, schema

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#598]
To support ongoing work on map representations, the following information must be included in the response from the open street map preprocessor:

* Number of lanes in a street
* Presence of traffic lights
* Speed limit
* Presence of tactile paving

Since this list will likely need to be expanded eventually, we really ought to find a more generic way for including attributes from open street map in the responses.

**Comment by jeffbl** [comment]
@samueljohnsegun148 is this a duplicate of #608? If so, please close as duplicate. If it is not a duplicate, please describe the difference, or consolidate into a single issue.

**Comment by samueljohnsegun148** [comment]
Closing this because it is a duplicate of #608.
