### ISSUE TITLE
Design and implement a basic tactile graphic schema

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#599]
With the assistance of @JRegimbal and other team members, create a generic schema for a single tactile graphic. This will contain only one "layer" and should be agnostic to the aspect ratio or pin density of a pin array device. This is a base data structure for reuse and refinement later.

**Comment by VenissaCarolQuadros** [comment]
As discussed with Juliette, single-layer graphics are to be represented by a simple svg with one or more shapes:
Example:
```
<svg width="200" height="100" viewbox="0 0 200 100"> 
  <circle cx="100" cy="50" r="20" fill="black"/>
</svg>
```

- Description could be given in `aria-description` similar to that in the layered tactile schema. 

As a rendering:
```{
    "type_id": "ca.mcgill.a11y.image.renderer.TactileSVG",
    "data": {
        "graphic": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjEwMCIgdmlld2JveD0iMCAwIDIwMCAxMDAiPgogIDxjaXJjbGUgY3g9IjEwMCIgY3k9IjUwIiByPSIyMCIgZmlsbD0iYmxhY2siLz4KPC9zdmc+"
    },
    "description": "An example tactile SVG of size 200 by 100 that displays a circle in the center."
}```

**Comment by JRegimbal** [comment]
Reopening as schemas not yet merged!
