### ISSUE TITLE
Provide Common Object Sortings

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#60]
Discussion with Florian brought up the usefulness of having common sortings of detected objects (e.g., left-right, top-bottom, area, confidence) available before SuperCollider. It seems to me like this information may end up being very useful across handlers and would make sense as either a separate preprocessor (similar to grouping) or a feature of object detection if it's truly something that is ALWAYS needed.

Personally I lean towards a lightweight preprocessor. @rohanakut any thoughts on this?

**Comment by rohanakut** [comment]
Closing this issue since [PR268](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/268) is merged.
