### ISSUE TITLE
Schemas should be loaded near the end of the build

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#61]
Docker build caches rely on a lack of changes in all previous steps. Because of this, it's beneficial to have the parts that change infrequently (if ever) at the beginning and the parts that change frequently at the end (see [leveraging the build cache](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache)).

This issue requires all images that use the schemas to copy them in *after* all dependencies are installed at least. Dependency installation can be very time consuming and take up a lot of space, so it's best to use the cache if possible.

- [x] orchestrator
- [x] supercollider
- [x] espnet-tts
- [x] hello-preprocessor
- [x] hello-handler
- [x] object-detection
- [x] object-grouping
- [ ] scene-detection
- [ ] hello-tts-handler
- [ ] generic-tts-handler

**Comment by jeffbl** [comment]
@JRegimbal beyond taking more time to build, does this have any impact on things like github resources we're consuming, that may eventually get us into trouble?

**Comment by JRegimbal** [comment]
AFAIK, there isn't currently any storage/bandwidth quota we need to worry about running up against with images in public repositories.
