### ISSUE TITLE
STORY: as an IMAGE user interested in photographs, I want to know whether a photo is actually a collage so that I can know if the results may be unreliable

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#646]
Now that we have the ability to detect collages, I think we should incorporate into handlers in two steps:
1. Add a phrase at beginning if the collage detector things a graphic is a collage, "This may be a collage of multiple photos." Could also add something like "so results may be confusing" or something as a further warning, since we don't break the collage down into parts and describe each.
2. If after using it for a while, it seems to be accurate and rarely marks non-collages as collages, and the results for collages are more confusing than useful, remove the rest of the description, just telling the user it is likey a collage, so we cannot describe it accurately.

@Cybernide does this make sense? Wording changes?

**Comment by Cybernide** [comment]
Dropping my assignment since I think this is the right wording

**Comment by jeffbl** [comment]
@rianadutta Moving to next sprint, but if not realistic to complete, let's move to backlog?
