### ISSUE TITLE
STORY: As a preprocessor developer, I want to find classification models and image datasets so that I can determine feasibility of training a machine learning model to recognize human action in a photograph.

### ISSUE THREAD

**Issue by gabriellemacinnes** [Shared-Reality-Lab/IMAGE-server#664]
- [x] Determine relevant evaluation metrics based on value to the user
- [x] Find human action image datasets
- [x] ~Decide best method for creating a new dataset if sufficient data is not already available~
- [x] Literature review to find the optimal model for classification
- [x] Document reasons behind choices and present at sprint demo day

**Comment by jeffbl** [comment]
@gabriellemacinnes If this is completed, you can close it. There should be a link to your document, which needs to be someplace accessible, e.g., the IMAGE google drive folder. Please let me know if you have questions. Thanks!
