### ISSUE TITLE
STORY: As a accessibility researcher, I want to create a pilot study so that I can make informed designed decisions on my user study.

### ISSUE THREAD

**Issue by emmanuelwilson** [Shared-Reality-Lab/IMAGE-server#665]

**Comment by jeffbl** [comment]
@emmanuelwilson Should this roll into Jun19 sprint?

**Comment by emmanuelwilson** [comment]
Might be best if you don't mind! Its coming along nicely but I don't technically have a fully functioning Haptic + sound experience just yet!

**Comment by Cybernide** [comment]
Let me know if I should move to a different milestone @emmanuelwilson
