### ISSUE TITLE
STORY:  As a accessibility researcher, I want to submit an REB and recruit participants so that I can start data acquisition for my study.

### ISSUE THREAD

**Issue by emmanuelwilson** [Shared-Reality-Lab/IMAGE-server#704]
- [x] Submit REB 
- [x] Send out recruitment add

**Comment by Cybernide** [comment]
Moving to Almost Done since I'm thinking we're close to the final version. Let me know if you think it'll take up the rest of the sprint and I'll reclassify accordingly
