### ISSUE TITLE
Pie charts take 1.5 minutes to render

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#712]
Production extension against unicorn (also occurs in production)

Go to this page:
https://www.inspq.qc.ca/covid-19/donnees/age-sexe

Scroll down to a pie chart
"Interpret this chart with IMAGE"

Play returned spatialized rendering

Note: Total time to render is 1:25
Note: 1% wedge takes quite a few seconds to render

Expect: Entire rendering is bounded to a reasonable rendering time.

**Comment by JRegimbal** [comment]
Values reported are raw numbers of deaths while the supercollider code was written assuming that only percentages would be recorded.
