### ISSUE TITLE
French TTS (`espnet-tts-fr`) struggles with numerical numbers

### ISSUE THREAD

**Issue by notkaramel** [Shared-Reality-Lab/IMAGE-server#723]
As title suggests, the French TTS is having a hard time generating audio for large number input, in numeric form. Here in this example, the text output from the translation is (from [Etherscan](https://etherscan.io/chart/ethersupplygrowth)): 

- "Graphique de croissance de l'offre d'Ether. x Axis,Time,du 30 juillet 2015 au 15 juin 2023. y Axis,Ether Supply,du 72049306.59375 au 120532870.54151082"

Here is the audio generated: [French TTS Rendering (via Google Drive)](https://drive.google.com/file/d/18nrvcSZLEdWy5ThsalGDsdlzF0JgH6BP/view?usp=sharing).

Notice that the service struggles to say "2015", "2023", and most of the remaining large numbers.

**Comment by notkaramel** [comment]
French TTS also struggles with describing data. Example from a pie chart from https://www.inspq.qc.ca/covid-19/donnees/age-sexe

![image](https://github.com/Shared-Reality-Lab/IMAGE-server/assets/24505220/e729dce8-fb1f-4cec-b268-aae589790110)

Audio: [Pie Chart Rendering (via Google Drive)](https://drive.google.com/file/d/12rpbvbkSSlyMhD_8hPZNM56a7gZqbPDU/view?usp=sharing)

Note that the French TTS struggles to say concatenated numbers or with decimal point/comma, like (in **bold**):
- "**40-49** ans, **15,76** pour cent"
- "**50-59** ans, **12,70** pour cent"
- ...

**Comment by notkaramel** [comment]
Weird case: French TTS can not say "2" or "3" in French.

Graphic:
![Image from IMAGE](https://image.a11y.mcgill.ca/pages/imgs/pexels-mikhail-nilov-6981101.jpg)

Text (in French): "Cette photo intérieure contient les objets ou personnes suivants: 3 livres, 3 téléviseurs, 2 personnes, 2 chaises, un téléphone portable, une souris, et un clavier."

Audio: [Photo rendering (via Google Drive)](https://drive.google.com/file/d/1X225D5rOorS-zRVYr6ITGufCyan63iKI/view?usp=sharing)

Notice how French TTS said "3" as "et tres" (I think), and "2" as "two". "2 personnes" should have been "deux personnes" but it was "two personnes".

**Comment by jeffbl** [comment]
Put in Jul10 sprint for investigation of possible solutions. Particularly important for charts!

**Comment by notkaramel** [comment]
Moved to sprint Jul31 to investigate and resolve during this sprint instead

**Comment by notkaramel** [comment]
- In order to help French TTS speaks numbers, I added the [**num2words**](https://pypi.org/project/num2words/) library. It allows number conversion to multiple language, would definitely benefit future addition of other languages with similar implementation.
- There are quite a wide range of possibilities/cases that need to be taken into consideration: 
- > note that the condition flow is: break down a long string of text into segments. For each segment, we check if the string could potentially a number, or if it's a syntax that involves numbers. 
  - **Case 0** (simplist): the number is an integer or a float ➡️ convert directly to text
  - **Case 1**: Float number. Due to French notation of decimal is a comma "," instead of a dot ".", we have to revert the change that `multilang-support` does while translating and check if the string is a float number by type casting.
  - **Case 2**: Range. Can see above from the pie chart example with age range, where "20-29" could not be directly intepreted as numbers. 
  - **Case 3** (edge): The number is next to a comma/dot. Occured with the Etherium example above: "2023.". Since we are processing substrings of the whole sentence, solving **Case 0** also solve this case. 
  - **Case 4**: ?

- Those are the cases for the examples of this issue, and surely I am not covering every possible cases that may occur.

**Comment by notkaramel** [comment]
Moved (again) to sprint Aug 21st because I'm a bit behind schedule and Regex took me a while to understand. Apologies!
