### ISSUE TITLE
openstreetmap preprocessor not handling lack of API key appropriately?

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#731]
CONFIGURATION ISSUE: @samueljohnsegun148  I'm testing on unicorn using the map on the [tech page of the IMAGE website](https://image.a11y.mcgill.ca/pages/tech.html), and I'm seeing an error in the logs that openstreetmap is not finding an API key. Could you look into fixing any problems with the API key on unicorn?

`image-openstreetmap-1                  | 2023-07-03T11:52:19.877596123Z ERROR:root:Unable to find API Key`

MAIN ISSUE: If it can't find an API key, it should probably just return at that point, but I still see:

`image-openstreetmap-1                  | 2023-07-03T11:52:19.877611813Z ERROR:root:Unable to find Latitude/Longitude `

implying that it is continuing to try and run even if it knows that there is no API key it can use. Suggest this should exit as soon as it knows it cannot find an API key? Is this an appropriate message reflecting what is actually happening? Note that the autour preprocessor is returning results, so I'm assuming that the lat/lng are legitimate from the request, so there may be something else going on here?

While revising, please review debug logging and error checking overall - I cannot test it since it doesn't seem to be working due to the API key issue.

**Comment by Cybernide** [comment]
Have been told that this is awaiting a pull request from @JRegimbal - could you please confirm?

**Comment by samueljohnsegun148** [comment]
@Cybernide Yes, two pull requests (i.e., #732 and the other in the repo for IMAGE-website), to address this, are awaiting approval. I decided not to directly link this issue since they are two separate pull requests and would probably be merged sequentially.

**Comment by jeffbl** [comment]
@samueljohnsegun148 I see #732 has been merged, and I don't see another pending PR. Is this completed? If so, can it be closed?

**Comment by samueljohnsegun148** [comment]
@jeffbl Yes. It can be closed.

**Comment by Cybernide** [comment]
@jeffbl Closing
