### ISSUE TITLE
STORY: As a Francophone IMAGE user, I want the extension to be thoroughly tested and validated, so that I can have a seamless experience in my preferred language.

### ISSUE THREAD

**Issue by notkaramel** [Shared-Reality-Lab/IMAGE-server#736]
### 1. French TTS
- Resolving Shared-Reality-Lab/IMAGE-server#723 
- PR: Shared-Reality-Lab/IMAGE-server#739 

### 2. Code clean-up + Documentation for all `multilang` related components
- Perform functionality testings & documentation on all components within IMAGE that involves multilang: , many handlers, French TTS, UI elements in the browsers
  - [x] `multilang-support` translation service
  - [x] #743
    - [x] Translation to other languages than French
  - [x] French TTS: resolve occuring/weird issues
  - [ ] UI Elements: make sure the translation make sense 
- Ensure the extension works on different OSes, browsers, with different parameters taken into account.
- Quickstart (new), French tutorial and feedback form: Shared-Reality-Lab/IMAGE-browser#340

### 3. French support testing 
- Design a testing plan: 
  - [x] Test extension is up-to-date
    - [x] Must have the language selection box
    - [x] Must be able to change visible UI element to French if the browser is set to French
    - [ ] (Optional) Have the new audio cue
  - [ ] Server services are up-to-date: Pending PR #743 
    - [x] `multilang-support` microservice
    - [x] `espnet-tts-fr` with regex and num2words filtering
    - [x] `photo-audio-handler` able to translate the segment's title
    - [x] `high-chart` handler
    - [x] `autour-handler`
  - [ ] #753
    - Record the system/browser settings, tests performed, and rating on quality of renderings (are they comprehensible? audible? grammatically correct?)
    - Make sure the experience in French is as seamless as possible
  - [ ] Make changes accordingly.

### 3. Push to production
- Ensure both the server-side and client-side components works well on `unicorn` and the test version of the extension.
- Changing tags of microservices, handlers to push to `pegasus`
- Resolves #152 
- Resolves #663 (oh no it's my last summer sprint 😿)

**Comment by notkaramel** [comment]
@jeffbl There are some lingering work items that will be small tweaks for the next update. Technically speaking, the epic is fulfilled/completed. Should I have another story to the epic, or should I close the epic and work on the tweaks individually?

**Comment by jeffbl** [comment]
French support is deployed to production, so I agree the epic is complete, and I would close it. Additional tweaks and bug fixes should be handled as separate work items.

**Comment by notkaramel** [comment]
Gotcha! I'm closing the story and epic. Unfinished related work items will be resolved separately.
