### ISSUE TITLE
As a handler developer, I want to build a preprocessor which classifies action from a photograph and outputs the action class, so that further information about activity in images can be provided to blind or low-vision IMAGE users.

### ISSUE THREAD

**Issue by gabriellemacinnes** [Shared-Reality-Lab/IMAGE-server#738]
- [x] create new docker image
- [x] create schema to validate output
- [x] create handler to display svg output

**Comment by Cybernide** [comment]
Added you as assignee! (Unless you were looking at someone else to do this, in which case, please reassign)

**Comment by gabriellemacinnes** [comment]
No that was for a different preprocessor, I just forgot to assign myself.

**Comment by Cybernide** [comment]
Moving this to the next sprint, please let me know if you can get it done sooner, though!
