### ISSUE TITLE
STORY: As a blind/low-vision IMAGE user, I want the human action recognition model to be more robust so that I can be provided with more accurate information about actions portrayed in graphics.

### ISSUE THREAD

**Issue by gabriellemacinnes** [Shared-Reality-Lab/IMAGE-server#746]
- [x] Source additional images to expand action dataset
- [x] Literature review on vision transformers for classification and how to improve results
- [x] Explore the best way to convey action information to users

**Comment by jeffbl** [comment]
@gablavoiie is this done now? if so, can it be closed? Otherwise please specify what remains to be done on this story, given everything is marked complete. thanks!
