### ISSUE TITLE
STORY: As a haptic authoring tool designer, I want to create a compelling demonstration of haptic effects, so that designers can brainstorm experiences based on realistic Haply 2diy capabilities.

### ISSUE THREAD

**Issue by JRegimbal** [Shared-Reality-Lab/IMAGE-server#771]

**Comment by jeffbl** [comment]
@JRegimbal I'd say this is complete in terms of functionality between the four-circle demo + the line graph with error regions. Is there more to do on this before closing? Can we get the code checked in somewhere, so that you do not have to keep zipping it up and sending it to people? :)
