### ISSUE TITLE
Pie charts sonify all wedges the same duration in production

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#777]
Go to pie chart on this site
https://www.inspq.qc.ca/covid-19/donnees/age-sexe
Get rendering from production (pegasus)
NOTE: Each wedge sonification takes the same amount of time, despite different pie sizes
Get rendering from test (unicorn)
NOTE: Wedge sonifications correctly vary by wedge size
EXPECT: production behaves like unicorn

Guessing a fix never got tagged and put into production?
Did a `docker compose pull` on pegasus, and `image-pegasus-cim-mcgill-ca` did update, but no change in behavior for this issue.

**Comment by JRegimbal** [comment]
The fix in #713 was never applied in a release for the supercollider service. Version 0.3.0 of the service was created based on the current state and includes this fix.
