### ISSUE TITLE
Make physical adjustments to 2diy3g devices that have been assembled so far

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#785]
Breaking this out of #782 as a separate work item

Task is to make sure all of the assembled devices are behaving in the same (correct) way vs. a reference device from @JRegimbal, as there were some issues following the initial assembly.

**Comment by LukeBebee** [comment]
Using Juliette's device as a guide (3.1-A), we made adjustments to devices 3.1-D, E, F, G, H. They all now feel similar to 3.1-A.

The main adjustments we made were:
- Tightening all arm screws including their connections to the motors
- Adjusted the arm joint screws to make sure they are even and provide minimal resistance
- Increased the clearance between the arm and the base

Issues:
- Left motor on G squeaks
- Right arm or motor on H squeaks

**Comment by LukeBebee** [comment]
F, D, and E have some resistance near the base of the device, E having the most. A still feels the best.

**Comment by LukeBebee** [comment]
In addition to making the physical adjustments to the 2diys, we also conducted some testing on their performance. As the physical adjustments are completed, I will close out this task.
