### ISSUE TITLE
STORY: As a 2diy photo experience developer, I want to create sample 2diy texture experiences to test effectiveness of specific features.

### ISSUE THREAD

**Issue by LukeBebee** [Shared-Reality-Lab/IMAGE-server#792]
- [ ] Create sample haptic experiences that include the following features: sound/earcons, unique effects from the repository Jeremy sent (such as plucking), user guidance
- [x] Create our own segmentation with the image contour exporter tool in the IMAGE-UX repository
- [x] Work with Juliette and Emmanuel to determine if we can help develop or use an in-house-developed physics engine for experiences
- [x] Work out potential bug that is preventing our current demo from running on all developers’ machines

**Comment by LukeBebee** [comment]
Still resolving a bug that is messing up our audio-haptic demos. 
Working on a demo using Juliette's haptic authoring. This will make it easier to create feedback using Juliette's authoring tools, then apply them to real demos in the future.
Plucking experience is not working completely as expected, unsure of why as of now. The experience is too erratic for a good demo.

**Comment by LukeBebee** [comment]
This sprint, most of our time was spend on our mid-project report we had to submit, and getting ready for the Haply demo, so we didn't finish any of the demos we were working on.

**Comment by jeffbl** [comment]
If difficult to implement, I'm fine with it going in once we can start building actual experiences, hopefully by end of January. In the meantime, I'd suggest taking a step back to brainstorm very different potential alternatives to the straight-up texture mapping.

**Comment by LukeBebee** [comment]
Closing this out. The only unchecked task is the additional features. Some of them have been tested and didn't work quite right, and others are still in progress. The in progress features are described in the new story
