### ISSUE TITLE
STORY: As a 2diy haptic experience developer, I want to develop quality and diverse haptic experiences for the 2diy with the goal of testing the effectiveness of different experiences.

### ISSUE THREAD

**Issue by LukeBebee** [Shared-Reality-Lab/IMAGE-server#796]
- [x] Implement sound functionality into our current experiences.
- [x] Implement haptics based on parameters from Juliette’s haptic sketching program.
- [x] Hold a brainstorming session to determine what experiences we want to develop.
- [ ] Implement 4 experiences (one each) based on the brainstorming session and using the newly implemented capabilities.
- [x] Determine what is necessary to complete for a user study so we can test the effectiveness of our experiences with the 2diy.

**Comment by LukeBebee** [comment]
code into [the prototypes repo](https://github.com/Shared-Reality-Lab/IMAGE-prototypes) for safety and sharing!

**Comment by LukeBebee** [comment]
We are going to be utilizing this haptic texture toolkit in our development!

The haptic texture toolkit: https://repository.upenn.edu/entities/publication/c1b8168b-b8a7-4f22-9e38-6430c233a600 
The paper on it: https://ieeexplore.ieee.org/document/6775475

**Comment by jeffbl** [comment]
Based on your priorities set with Jeremy, is this still going, or are the one-off experiences you demoed for things like the waterfall all checked in and this is basically complete?

**Comment by LukeBebee** [comment]
This story was never fully completed, and was shadowed by our efforts to get things ready for a study. Only one experience was made before the priorities shifted and it was never fine-tuned.
