### ISSUE TITLE
Clarify status of project/handlers/preprocessors in README files

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#816]
To avoid confusion, add text to server repository READMES concerning what is "beta" and what is "alpha" and what that means. I propose adding the following to the server repository overall README:

> IMAGE as a whole is in beta. McGill operates a public server that the IMAGE browser extension uses by default, which runs various preprocessors and handlers that the IMAGE team deems ready for testing by end users. There are many additional components in the IMAGE code repositories, some of which are not considered ready for use. These are made available for researchers and others as alpha code that requires further refinement before it is likely usable in practice. Caveats are generally noted in the README for each component. If you are a researcher evaluating or building on IMAGE, we ask that you distinguish between beta and alpha code when referencing specific IMAGE components and functionality. As a general reference for the IMAGE server architecture, please use:
> 
> Juliette Regimbal, Jeffrey R. Blum, and Jeremy R. Cooperstock. 2022. IMAGE: a deployment framework for creating multimodal experiences of web graphics. In Proceedings of the 19th International Web for All Conference (W4A '22). Association for Computing Machinery, New York, NY, USA, Article 12, 1–5. https://doi.org/10.1145/3493612.3520460

Then, in each preprocessor/handler README, mark either:

> Beta quality: Useful enough for testing by end-users.
> 
> Alpha quality: Insufficiently refined to be tested by end-users.

@Cybernide  I'd then also propose that we have a blurb pointing from the IMAGE website / extension description telling researchers to please note information at server wiki homepage, e.g.:

> If you are a researcher using or evaluating IMAGE, please make sure to read the [IMAGE Server repository README].

Taking feedback on approach and implementation before putting this up, but would like to do so after sprint meeting on Wednesday. Ping to @JRegimbal @Cybernide @jaydeepsingh25 in particular for comments.

**Comment by JRegimbal** [comment]
This seems reasonable to me! I can't think of any situations where we would need another level of component "maturity". Although I think that drawing the line between alpha and beta in practice might be somewhat difficult...
