### ISSUE TITLE
test server not working with extension

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#819]
After updating unicorn to use TLS again now that it is on its own public IP, when using the extension against http://unicorn.cim.mcgill.ca/image, the request is received, and all of the preprocessors/handlers seem to trigger (watching server logs), but before they are even done running, the extension pops up
`An error occurred while trying to connect to the IMAGE server. Please try again later. If this error persists, please contact the IMAGE team by email at [image@cim.mcgill.ca](mailto:image@cim.mcgill.ca).`

error window. Looking at traefik log, it shows:

` level=debug msg="'499 Client Closed Request' caused by: context canceled"`

which is apparently a nginx error saying the client closed the request before a result was received.

I've poked around a bit, but don't see an obvious flaw.

**Comment by jeffbl** [comment]
Works fine on pegasus, so I don't think it is an extension issue, and that hasn't changed in a while, so most likely something with traefik/nginx?

**Comment by JRegimbal** [comment]
After initial investigation, this appears to be due to the version of traefik we use on Unicorn being updated. Checking for changes between versions to find how to resolve this.

**Comment by JRegimbal** [comment]
This was specifically an issue caused by the `LingeringTimeout` option being introduced in v2.11.1 of traefik with a default timeout of 2 s. `LingeringTimeout` was removed in v2.11.2, so I have simply updated to a newer version.

No changes to IMAGE components were necessary.
