### ISSUE TITLE
depth-map-gen preprocessor weights are no longer available for download

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#821]
While fixing some build issues, it turned out that the weights being downloaded in the `depth-map-gen` preprocessor Dockerfile are no longer available:

https://cloudstor.aarnet.edu.au/plus/s/lTIJF4vrvHCAI31/download

@JRegimbal extracted the weights we need from what we'd already downloaded, so we have a copy for our own use. However, if this project is deprecated, others will have trouble getting these unless we host them ourselves. Before looking into that, it is probably worth checking whether there is another model being updated that we could easily switch to.

**Comment by emmanuelwilson** [comment]
Still working on a solution, I don't have great internet on the train atm. It appears that the link to download the weights has changed! Hopefully it is still Docker-able but I suspect they made it harder specifically for machine use (there is a wall that requires a button click). Looking to see if there is a workaround. IF that is the case and we can't download it directly on build, is there a way to store the weights locally? They don't seem be very large (we'll see after decompression).

**Comment by jeffbl** [comment]
It would be preferable that anyone external would be able to access the weights directly, of course. If they are still hosted elsewhere but not directly accessible, it would be a bit messy, but we could:
1. cache them locally for our own builds (there is a directory for this that we get from Sharepoint, and I then move to unicorn/pegasus)
2. document how external users can get their own local copy, probably in preprocessor README plus in any files where it is used as comments.

If the project has gone inactive, it is also worth a brief look into alternatives. e.g., did anyone fork it? Create an alternative that is actively being moved forward?

[This link](https://www.owl3d.com/blog/2d-to-stereoscopic-3d-with-ai-depth-map-from-a-single-image) points to others I know you already considered, but also to another one called [ZoeDepth](https://github.com/isl-org/ZoeDepth), although it looks like that might be a one time code dump that isn't being updated.
