### ISSUE TITLE
people handler: review issues and decide on existing code vs. GPT approach for ongoing work in this area

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#825]
When reviewing the [people-handler](https://github.com/Shared-Reality-Lab/IMAGE-server/tree/main/handlers/people-handler), a [number of issues were flagged](https://github.com/Shared-Reality-Lab/IMAGE-server/pull/779).

The task is to look at this broadly, to decide whether to try and improve the current codebase into something deployable, or else look at more current GPT-style approaches for accomplishing the goal of providing end users with information about specific people in photographs. Notes:

- The code review from the most recent PR for this pointed to three key issues. It isn't clear how much work these would be to fix, and whether there are additional significant issues yet to be discovered :
  - Lack of comments and issues with code structure, magic numbers, etc.
  - Apparent errors in end-user results due to (for example) code containing long chains of difficult to interpret if statements with multiple conditions
  - potential refactoring to move interpretation from handler into associated preprocessors, where they could be used by other handlers
- The entire premise of attributing emotion and other details to specific people is so fraught that large companies are deprecating this functionality. [Some discussion of this in this issue](https://github.com/Shared-Reality-Lab/IMAGE-server/issues/528).
- No matter how we deploy this type of functionality, we need to verify that it is not biased in ways that will risk very undesirable interpretations. This alone might move us toward a vetted cloud solution.

**Comment by jeffbl** [comment]
@redyukunma I'd like to make a call on deprecating these or not as soon as possible, since there has been some confusion on whether these should be kept updated for security updates, etc. If we're going to deprecate them, I'd like to do it asap.

My current take is that we should likely deprecate:
- people-handler
- emotion-recognition

But these two I'm less clear about, and if they are in decent technical shape, could potentially be kept if likely to be useful, even though we won't have a handler to express the results:
- clothing-detector
- celebrity-detector

**Comment by jeffbl** [comment]
Assigned to @jeffbl to do the deprecation

**Comment by jeffbl** [comment]
As discussed, people-handler and emotion-recognition preprocesser have been moved to deprecated folders. I have also disabled the workflows for both.

Assigning to @JRegimbal for final check before closing.

**Comment by JRegimbal** [comment]
Oh interesting, it doesn't seem to make any changes in git so I didn't notice. I suppose this works!
