### ISSUE TITLE
collage detector: decide whether to move to production (with list of incorrect detections)

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#826]
collage detector is in testing on unicorn, and if the preprocessor is running, it is expressed in the photo-audio handler telling the user that the photo looks like a collage, so results might be weird. I've seen no issues with performance or code errors, but it is of course imperfect in its detection, including with false positives where it says a photo is a collage when it is not. This issue is to track these errors so we can decide if it is reliable enough to deploy on pegasus.

False positives:
https://image.a11y.mcgill.ca/pages/imgs/pexels-mikhail-nilov-6981101.jpg  (from the IMAGE homepage!)
[Bookshelves](https://preview.redd.it/bookshelves-in-the-eaves-hard-to-photograph-v0-02nqgxjiql1d1.jpg?width=1920&format=pjpg&auto=webp&s=ce7b6519512b00e2668b24c358fee9cb8c01a7bd)
[Museum](https://cdn.britannica.com/51/194651-050-747F0C18/Interior-National-Gallery-of-Art-Washington-DC.jpg)
[Building with vertical pillars](https://media.cntraveler.com/photos/5a7b50d069c80815f37e604e/16:9/w_2560,c_limit/British-Museum__2018_00917427_001.jpg) 

False negatives:
[Marilyn face collage](https://kolajmagazine.com/content/wp-content/uploads/waverly-collage-makers-Marilyn.jpg) [@jeffbl opinion: this could reasonably by construed as not a collage, so I don't think this is a clear false negative.]

**Comment by jeffbl** [comment]
This issue is specific to the ML aspect of the collage-detector. Reassign to Yifan.

**Comment by AndyBaiMQC** [comment]
@jeffbl This could have some ramifications with textbook diagrams as the scenario of having lumps of 'sub-images' with clearly defined borders may appear. I'm continuing on prompt engineering and looking for ways to fine-tune if possible (or have a RAG style setup)

**Comment by AndyBaiMQC** [comment]
![Image](https://github.com/user-attachments/assets/d6397317-566f-4c56-864e-799823ad90af)

**Comment by jeffbl** [comment]
@JRegimbal please tag for production

**Comment by JRegimbal** [comment]
tagged and updated
