### ISSUE TITLE
Photos not being seen as photos means no useful renderings

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#829]
Please put links to photos here that are failing to be recognized properly. This is indicated by a log line like the following:

`semantic-segmentation-1           | 2024-05-29T19:23:16.875899574Z INFO:root:Not photograph content. Skipping...`

If you aren't sure if this is the issue causing you to get few/no results when you think you should, do NOT list it here, since it is a different root cause.

Two that came in from @VenissaCarolQuadros and @emmanuelwilson:

https://www.nytimes.com/2019/10/07/learning/why-is-it-important-for-people-with-different-political-beliefs-to-talk-to-each-other.html
https://menliving.org/wp-content/uploads/2022/05/getty_511618259_186076.jpeg

**Comment by jeffbl** [comment]
Was going to break this out specifically, but [this example](https://www.nytimes.com/2019/10/07/learning/why-is-it-important-for-people-with-different-political-beliefs-to-talk-to-each-other.html) from above is particularly insidious since as mentioned in #625, it means that since content-categorizer is tagging things incorrectly, if we move collage-detector later in the pipeline, valid collages of photos won't be picked up by collage-detector at all if it sees that content-categorizer doesn't think it is a photograph. Fuller discussion in #625, but wanted to make sure this particular aspect is covered here.

**Comment by jeffbl** [comment]
Further work is LLM tweaking, so no further work needed on this right now. Can be put into backlog once this is all merged and running in production.

@AndyBaiMQC please PR for merge to main, for testing on unicorn, before moving to production.

**Comment by jeffbl** [comment]
Also, move API key to a non-personal account on our open-webui instances

**Comment by AndyBaiMQC** [comment]
Status update:

- Public API key created (credits to @jeffbl)
- API cred file created on Unicorn under `/var/docker/image`, `[prod]` is already filled, and if you wish to test things ad-hoc, feel free to add your own API keys there (but make sure to delete them once you are done)
```
[prod]
jwt_token=
api_key=
# DO NOT leave your personal API key overnight         
# Add it, test and delete
[personal]
jwt_token=
api_key=
```
- No further tweaking on prompt engineering. Final debugging.
