### ISSUE TITLE
Design system for caching requests, e.g., if multiple clients ask for same graphic in short time window

### ISSUE THREAD

**Issue by jaydeepsingh25** [Shared-Reality-Lab/IMAGE-server#836]
The user story is created to implemented Caching mechanism so that IMAGE server can be scaled to address multiple clients at a moment efficiently. Relevant information available at https://github.com/Shared-Reality-Lab/IMAGE-server/issues/804

**Comment by jeffbl** [comment]
@jaydeepsingh25 I think we can close this now that caching is deployed on pegasus, and handle new issues as they arise. Please go ahead and resolve if you agree.
