### ISSUE TITLE
Update from traefik v2 -> v3

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#864]
Traefik v3 came out in early 2024. Unlike the V1->v2 update that was a disaster, they indicate they support v2 syntax and [transition should be smooth](https://traefik.io/blog/announcing-traefik-proxy-v3-rc/). Still would need to be tested on unicorn first!

Note that on pegasus, there are other projects that would need to be verified, such as the moodle.

Tasks:

- [x] update to traefik v3 on unicorn, see if things work
- [x] update traefik config to v3 syntax
- [ ] test more on unicorn
- [ ] deploy new configuration to production on pegasus.

**Comment by JRegimbal** [comment]
Pegasus updated
