### ISSUE TITLE
Test suite of images for testing

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#87]
Issues like #39 mean we should probably have a test suite of images that we test against regularly so that we catch boundary cases like:

- not finding any objects in the graphic (i.e., #39)
- very small graphics (e.g., 3x3 pixels)
- extremely busy images (e.g., with 1000 peope packed in)
- ???

The idea would be to test this set of graphics periodically to catch regressions or new issues.

**Comment by jeffbl** [comment]
Not sure if we've already done this, but worth investigating. If no immediate action necessary, we should put this in the README that we'd love to have examples for these boundary cases, and close this work item.

**Comment by jeffbl** [comment]
@rianadutta in slack you indicated you added some new graphics. If these adequately cover above cases, please briefly summarize here, then this can be closed, and we'll deal with other specific cases that arise via new work items. Thanks!

**Comment by rianadutta** [comment]
Test suite now contains at least 2 graphics where no output is given, 2 photos with over 1000 people and one very small graphic (3x10 pixels)
