### ISSUE TITLE
restoreunstable script fails on `git pull` due to missing ssh keys when run via cron

### ISSUE THREAD

**Issue by jeffbl** [Shared-Reality-Lab/IMAGE-server#875]
On unicorn, we have a script in `/etc/cron.daily/image_daily_cron` that runs `/var/docker/image/bin/restoreunstable` to make sure we pick up changes and reset the test server to a known-good state every morning. Right now, that does a `su jeffbl` so that it has permissions to do all the things, but this fails on `git pull` since it is trying to do a keypair authentication, and that fails since I use a keystore on my local machine being passed through, which is not accessible when running automatically in the cron job. The server repo is public, so this should not be blocking. Possible solutions here:

https://stackoverflow.com/questions/39687911/git-permission-error-on-a-public-repo

But I don't know if there are better options. I'm loathe to store keys on unicorn that give IMAGE repo access, since I don't consider unicorn secure.

**Comment by shahdyousefak** [comment]
- modified the `/var/docker/image/bin/restoreunstable` script to remove duplicate entries of /`var/docker/image/auditory-haptic-graphics-server` & `/var/docker/image/auditory-haptic-graphics-server/schemas`
- the script now pulls from the repository using HTTPS with the command `git remote set-url origin https://github.com/Shared-Reality-Lab/IMAGE-server.git`. This change avoids the need for an SSH keypair authentication, preventing errors related to SSH key configuration or agent issues during the automated pulls.
