### ISSUE TITLE
Memory leak on RAM for chart models

### ISSUE THREAD

**Issue by SiddharthRaoA** [Shared-Reality-Lab/IMAGE-server#99]
#93 
As mentioned in the GPU usage issue, unloading models to the RAM causes a memory leak. The memory held by these models in the RAM is not released when they're reloaded back to the GPU. This causes the RAM usage to accumulate with cycles of unloading and reloading. 

This is mostly because the code uses an old version of PyTorch which does not release the RAM after use. However, moving the entire code to a newer version of PyTorch causes a cmake error while building the layers written in c++ (which is very hard to debug). So @gp1702 and I tried to find a workaround for the issue, by manually deallocating the RAM memory or killing the process, but found no direct method to do so from inside the docker container.

We need to resolve this only if we're not fine with the 9s processing time on unicorn, and want to reduce it to 6s.

**Comment by jeffbl** [comment]
This preprocessor is deprecated, so this will not be fixed.
